DROP DATABASE IF EXISTS DBPInf;
CREATE DATABASE DBPInf;
use DBPInf;

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO (
	ID_USUARIO INT NOT NULL PRIMARY KEY auto_increment,
	NOMBRE VARCHAR(25) NOT NULL,
	APELLIDOS VARCHAR(25) NOT NULL,
	TLF_MOVIL VARCHAR(9) NOT NULL,
	TIPO_VIA VARCHAR(25) NOT NULL,
	CALLE VARCHAR(25) NOT NULL,
	NUMERO INT NOT NULL,
	PORTAL VARCHAR(5),
	TLF_FIJO VARCHAR(9),
	LOCALIDAD VARCHAR(25) NOT NULL,
	MUNICIPIO VARCHAR(25) NOT NULL,
	PAIS_NACIMIENTO VARCHAR(25) NOT NULL
);

DROP TABLE IF EXISTS ASIGNACION;
CREATE TABLE ASIGNACION (
	ID_ASIGNACION INT NOT NULL PRIMARY KEY auto_increment,
	ID_RESPONSABLE INT NOT NULL,
	ID_USUARIO INT NOT NULL,
    DESCRIPCION VARCHAR(25),
    FOREIGN KEY FK_RESPONSABLE1(ID_RESPONSABLE) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY FK_RESPONSABLE2(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

DROP TABLE IF EXISTS ROL;
CREATE TABLE ROL (
	ID_ROL INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(25) NOT NULL,
	DESCRIPCION VARCHAR(25)
);

DROP TABLE IF EXISTS ROLES;
/* Tabla relacion n:n entre usuario y rol */
CREATE TABLE ROLES (
	ID_USUARIO INT NOT NULL,
	ID_ROL INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_ROL),
    FOREIGN KEY FK_ROLES1(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY FK_ROLES2(ID_ROL) REFERENCES ROL(ID_ROL)
);

DROP TABLE IF EXISTS MEDICIONES;
CREATE TABLE MEDICIONES (
	ID_MEDICION INT NOT NULL PRIMARY KEY,
	ID_USUARIO INT NOT NULL,
	SENSOR VARCHAR(25) NOT NULL,
	MEDICION VARCHAR(25) NOT NULL,
    FOREIGN KEY FK_MEDICIONES(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

DROP TABLE IF EXISTS ACCION;
CREATE TABLE ACCION (
	ID_ACCION INT NOT NULL PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(25)
);

DROP TABLE IF EXISTS HISTORICO;
CREATE TABLE HISTORICO (
	ID_HISTORICO INT NOT NULL PRIMARY KEY auto_increment,
    ID_USUARIO INT NOT NULL,
	ID_ACCION INT NOT NULL,
	CAMBIO_ANTIGUO VARCHAR(50) NOT NULL,
	CAMBIO_NUEVO VARCHAR(50) NOT NULL,
    FOREIGN KEY FK_HISTORICO1(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY FK_HISTORICO2(ID_ACCION) REFERENCES ACCION(ID_ACCION)
);