DROP DATABASE IF EXISTS DBPInf;
CREATE DATABASE DBPInf;
use DBPInf;

CREATE TABLE IF NOT EXISTS USUARIO (
	ID_USUARIO INT NOT NULL PRIMARY KEY auto_increment,
	NOMBRE VARCHAR(25) NOT NULL,
	APELLIDOS VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PAIS VARCHAR(25) NOT NULL,
    LOCALIDAD VARCHAR(25) NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    TLF_MOVIL VARCHAR(9) NOT NULL,
	TLF_FIJO VARCHAR(9),	
    NOMBRE_USUARIO VARCHAR(25) NOT NULL,
    CONTRASENA_USUARIO VARCHAR(256) NOT NULL,
    SAL VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASIGNACION (
	ID_ASIGNACION INT NOT NULL PRIMARY KEY auto_increment,
	ID_RESPONSABLE INT NOT NULL,
	ID_USUARIO INT NOT NULL,
    DESCRIPCION VARCHAR(25),
    FOREIGN KEY FK_RESPONSABLE1(ID_RESPONSABLE) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY FK_RESPONSABLE2(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS ROL (
	ID_ROL INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(25) NOT NULL,
	DESCRIPCION VARCHAR(25)
);

/* Tabla relacion n:n entre usuario y rol */
CREATE TABLE IF NOT EXISTS ROLES (
	ID_USUARIO INT NOT NULL,
	ID_ROL INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_ROL),
    FOREIGN KEY FK_ROLES1(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY FK_ROLES2(ID_ROL) REFERENCES ROL(ID_ROL)
);

CREATE TABLE IF NOT EXISTS MEDICIONES (
	ID_MEDICION INT NOT NULL PRIMARY KEY,
	ID_USUARIO INT NOT NULL,
	SENSOR VARCHAR(25) NOT NULL,
	MEDICION VARCHAR(25) NOT NULL,
    FOREIGN KEY FK_MEDICIONES(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS ACCION (
	ID_ACCION INT NOT NULL PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS HISTORICO (
	ID_HISTORICO INT NOT NULL PRIMARY KEY auto_increment,
    ID_USUARIO INT NOT NULL,
	ID_ACCION INT NOT NULL,
	CAMBIO_ANTIGUO VARCHAR(50) NOT NULL,
	CAMBIO_NUEVO VARCHAR(50) NOT NULL,
    FOREIGN KEY FK_HISTORICO1(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY FK_HISTORICO2(ID_ACCION) REFERENCES ACCION(ID_ACCION)
);

CREATE TABLE IF NOT EXISTS `PROVINCIAS` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PROVINCIA` VARCHAR(255) COLLATE UTF8_SPANISH_CI NOT NULL
  PRIMARY KEY (`ID`)
) ENGINE=MYISAM  DEFAULT CHARSET=UTF8 COLLATE=UTF8_SPANISH_CI CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC AUTO_INCREMENT=53 ;

--
-- VOLCADO DE DATOS PARA LA TABLA `PROVINCIAS`
--

INSERT INTO `PROVINCIAS` (`ID`, `PROVINCIA`,) VALUES
(1,'ÁLAVA'),
(2,'ALBACETE'),
(3, 'ALICANTE'),
(4, 'ALMERÍA'),
(5, 'ÁVILA'),
(6, 'BADAJOZ'),
(7, 'ILLES BALEARS'),
(8, 'BARCELONA'),
(9, 'BURGOS'),
(10, 'CÁCERES'),
(11, 'CÁDIZ'),
(12, 'CASTELLÓN'),
(13, 'CIUDAD REAL'),
(14, 'CÓRDOBA'),
(15, 'A CORUÑA'),
(16, 'CUENCA'),
(17, 'GIRONA'),
(18, 'GRANADA'),
(19, 'GUADALAJARA'),
(20, 'GUIPÚZCOA'),
(21, 'HUELVA'),
(22, 'HUESCA'),
(23, 'JAÉN'),
(24, 'LEÓN'),
(25, 'LLEIDA'),
(26, 'LA RIOJA'),
(27, 'LUGO'),
(28, 'MADRID'),
(29, 'MÁLAGA'),
(30, 'MURCIA'),
(31, 'NAVARRA'),
(32, 'OURENSE'),
(33, 'ASTURIAS'),
(34, 'PALENCIA'),
(35, 'LAS PALMAS'),
(36, 'PONTEVEDRA'),
(37, 'SALAMANCA'),
(38, 'SANTA CRUZ DE TENERIFE'),
(39, 'CANTABRIA'),
(40, 'SEGOVIA'),
(41, 'SEVILLA'),
(42, 'SORIA'),
(43, 'TARRAGONA'),
(44, 'TERUEL'),
(45, 'TOLEDO'),
(46, 'VALENCIA'),
(47, 'VALLADOLID'),
(48, 'VIZCAYA'),
(49, 'ZAMORA'),
(50, 'ZARAGOZA'),
(51, 'CEUTA'),
(52, 'MELILLA');



CREATE TABLE `PAISES` (
`ID` INT(11) NOT NULL AUTO_INCREMENT,
`ISO` CHAR(2) DEFAULT NULL,
`NOMBRE` VARCHAR(80) DEFAULT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 AUTO_INCREMENT=1 ;
 
INSERT INTO `PAISES` VALUES(1, 'AF', 'AFGANISTÁN');
INSERT INTO `PAISES` VALUES(2, 'AX', 'ISLAS GLAND');
INSERT INTO `PAISES` VALUES(3, 'AL', 'ALBANIA');
INSERT INTO `PAISES` VALUES(4, 'DE', 'ALEMANIA');
INSERT INTO `PAISES` VALUES(5, 'AD', 'ANDORRA');
INSERT INTO `PAISES` VALUES(6, 'AO', 'ANGOLA');
INSERT INTO `PAISES` VALUES(7, 'AI', 'ANGUILLA');
INSERT INTO `PAISES` VALUES(8, 'AQ', 'ANTÁRTIDA');
INSERT INTO `PAISES` VALUES(9, 'AG', 'ANTIGUA Y BARBUDA');
INSERT INTO `PAISES` VALUES(10, 'AN', 'ANTILLAS HOLANDESAS');
INSERT INTO `PAISES` VALUES(11, 'SA', 'ARABIA SAUDÍ');
INSERT INTO `PAISES` VALUES(12, 'DZ', 'ARGELIA');
INSERT INTO `PAISES` VALUES(13, 'AR', 'ARGENTINA');
INSERT INTO `PAISES` VALUES(14, 'AM', 'ARMENIA');
INSERT INTO `PAISES` VALUES(15, 'AW', 'ARUBA');
INSERT INTO `PAISES` VALUES(16, 'AU', 'AUSTRALIA');
INSERT INTO `PAISES` VALUES(17, 'AT', 'AUSTRIA');
INSERT INTO `PAISES` VALUES(18, 'AZ', 'AZERBAIYÁN');
INSERT INTO `PAISES` VALUES(19, 'BS', 'BAHAMAS');
INSERT INTO `PAISES` VALUES(20, 'BH', 'BAHRÉIN');
INSERT INTO `PAISES` VALUES(21, 'BD', 'BANGLADESH');
INSERT INTO `PAISES` VALUES(22, 'BB', 'BARBADOS');
INSERT INTO `PAISES` VALUES(23, 'BY', 'BIELORRUSIA');
INSERT INTO `PAISES` VALUES(24, 'BE', 'BÉLGICA');
INSERT INTO `PAISES` VALUES(25, 'BZ', 'BELICE');
INSERT INTO `PAISES` VALUES(26, 'BJ', 'BENIN');
INSERT INTO `PAISES` VALUES(27, 'BM', 'BERMUDAS');
INSERT INTO `PAISES` VALUES(28, 'BT', 'BHUTÁN');
INSERT INTO `PAISES` VALUES(29, 'BO', 'BOLIVIA');
INSERT INTO `PAISES` VALUES(30, 'BA', 'BOSNIA Y HERZEGOVINA');
INSERT INTO `PAISES` VALUES(31, 'BW', 'BOTSUANA');
INSERT INTO `PAISES` VALUES(32, 'BV', 'ISLA BOUVET');
INSERT INTO `PAISES` VALUES(33, 'BR', 'BRASIL');
INSERT INTO `PAISES` VALUES(34, 'BN', 'BRUNÉI');
INSERT INTO `PAISES` VALUES(35, 'BG', 'BULGARIA');
INSERT INTO `PAISES` VALUES(36, 'BF', 'BURKINA FASO');
INSERT INTO `PAISES` VALUES(37, 'BI', 'BURUNDI');
INSERT INTO `PAISES` VALUES(38, 'CV', 'CABO VERDE');
INSERT INTO `PAISES` VALUES(39, 'KY', 'ISLAS CAIMÁN');
INSERT INTO `PAISES` VALUES(40, 'KH', 'CAMBOYA');
INSERT INTO `PAISES` VALUES(41, 'CM', 'CAMERÚN');
INSERT INTO `PAISES` VALUES(42, 'CA', 'CANADÁ');
INSERT INTO `PAISES` VALUES(43, 'CF', 'REPÚBLICA CENTROAFRICANA');
INSERT INTO `PAISES` VALUES(44, 'TD', 'CHAD');
INSERT INTO `PAISES` VALUES(45, 'CZ', 'REPÚBLICA CHECA');
INSERT INTO `PAISES` VALUES(46, 'CL', 'CHILE');
INSERT INTO `PAISES` VALUES(47, 'CN', 'CHINA');
INSERT INTO `PAISES` VALUES(48, 'CY', 'CHIPRE');
INSERT INTO `PAISES` VALUES(49, 'CX', 'ISLA DE NAVIDAD');
INSERT INTO `PAISES` VALUES(50, 'VA', 'CIUDAD DEL VATICANO');
INSERT INTO `PAISES` VALUES(51, 'CC', 'ISLAS COCOS');
INSERT INTO `PAISES` VALUES(52, 'CO', 'COLOMBIA');
INSERT INTO `PAISES` VALUES(53, 'KM', 'COMORAS');
INSERT INTO `PAISES` VALUES(54, 'CD', 'REPÚBLICA DEMOCRÁTICA DEL CONGO');
INSERT INTO `PAISES` VALUES(55, 'CG', 'CONGO');
INSERT INTO `PAISES` VALUES(56, 'CK', 'ISLAS COOK');
INSERT INTO `PAISES` VALUES(57, 'KP', 'COREA DEL NORTE');
INSERT INTO `PAISES` VALUES(58, 'KR', 'COREA DEL SUR');
INSERT INTO `PAISES` VALUES(59, 'CI', 'COSTA DE MARFIL');
INSERT INTO `PAISES` VALUES(60, 'CR', 'COSTA RICA');
INSERT INTO `PAISES` VALUES(61, 'HR', 'CROACIA');
INSERT INTO `PAISES` VALUES(62, 'CU', 'CUBA');
INSERT INTO `PAISES` VALUES(63, 'DK', 'DINAMARCA');
INSERT INTO `PAISES` VALUES(64, 'DM', 'DOMINICA');
INSERT INTO `PAISES` VALUES(65, 'DO', 'REPÚBLICA DOMINICANA');
INSERT INTO `PAISES` VALUES(66, 'EC', 'ECUADOR');
INSERT INTO `PAISES` VALUES(67, 'EG', 'EGIPTO');
INSERT INTO `PAISES` VALUES(68, 'SV', 'EL SALVADOR');
INSERT INTO `PAISES` VALUES(69, 'AE', 'EMIRATOS ÁRABES UNIDOS');
INSERT INTO `PAISES` VALUES(70, 'ER', 'ERITREA');
INSERT INTO `PAISES` VALUES(71, 'SK', 'ESLOVAQUIA');
INSERT INTO `PAISES` VALUES(72, 'SI', 'ESLOVENIA');
INSERT INTO `PAISES` VALUES(73, 'ES', 'ESPAÑA');
INSERT INTO `PAISES` VALUES(74, 'UM', 'ISLAS ULTRAMARINAS DE ESTADOS UNIDOS');
INSERT INTO `PAISES` VALUES(75, 'US', 'ESTADOS UNIDOS');
INSERT INTO `PAISES` VALUES(76, 'EE', 'ESTONIA');
INSERT INTO `PAISES` VALUES(77, 'ET', 'ETIOPÍA');
INSERT INTO `PAISES` VALUES(78, 'FO', 'ISLAS FEROE');
INSERT INTO `PAISES` VALUES(79, 'PH', 'FILIPINAS');
INSERT INTO `PAISES` VALUES(80, 'FI', 'FINLANDIA');
INSERT INTO `PAISES` VALUES(81, 'FJ', 'FIYI');
INSERT INTO `PAISES` VALUES(82, 'FR', 'FRANCIA');
INSERT INTO `PAISES` VALUES(83, 'GA', 'GABÓN');
INSERT INTO `PAISES` VALUES(84, 'GM', 'GAMBIA');
INSERT INTO `PAISES` VALUES(85, 'GE', 'GEORGIA');
INSERT INTO `PAISES` VALUES(86, 'GS', 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR');
INSERT INTO `PAISES` VALUES(87, 'GH', 'GHANA');
INSERT INTO `PAISES` VALUES(88, 'GI', 'GIBRALTAR');
INSERT INTO `PAISES` VALUES(89, 'GD', 'GRANADA');
INSERT INTO `PAISES` VALUES(90, 'GR', 'GRECIA');
INSERT INTO `PAISES` VALUES(91, 'GL', 'GROENLANDIA');
INSERT INTO `PAISES` VALUES(92, 'GP', 'GUADALUPE');
INSERT INTO `PAISES` VALUES(93, 'GU', 'GUAM');
INSERT INTO `PAISES` VALUES(94, 'GT', 'GUATEMALA');
INSERT INTO `PAISES` VALUES(95, 'GF', 'GUAYANA FRANCESA');
INSERT INTO `PAISES` VALUES(96, 'GN', 'GUINEA');
INSERT INTO `PAISES` VALUES(97, 'GQ', 'GUINEA ECUATORIAL');
INSERT INTO `PAISES` VALUES(98, 'GW', 'GUINEA-BISSAU');
INSERT INTO `PAISES` VALUES(99, 'GY', 'GUYANA');
INSERT INTO `PAISES` VALUES(100, 'HT', 'HAITÍ');
INSERT INTO `PAISES` VALUES(101, 'HM', 'ISLAS HEARD Y MCDONALD');
INSERT INTO `PAISES` VALUES(102, 'HN', 'HONDURAS');
INSERT INTO `PAISES` VALUES(103, 'HK', 'HONG KONG');
INSERT INTO `PAISES` VALUES(104, 'HU', 'HUNGRÍA');
INSERT INTO `PAISES` VALUES(105, 'IN', 'INDIA');
INSERT INTO `PAISES` VALUES(106, 'ID', 'INDONESIA');
INSERT INTO `PAISES` VALUES(107, 'IR', 'IRÁN');
INSERT INTO `PAISES` VALUES(108, 'IQ', 'IRAQ');
INSERT INTO `PAISES` VALUES(109, 'IE', 'IRLANDA');
INSERT INTO `PAISES` VALUES(110, 'IS', 'ISLANDIA');
INSERT INTO `PAISES` VALUES(111, 'IL', 'ISRAEL');
INSERT INTO `PAISES` VALUES(112, 'IT', 'ITALIA');
INSERT INTO `PAISES` VALUES(113, 'JM', 'JAMAICA');
INSERT INTO `PAISES` VALUES(114, 'JP', 'JAPÓN');
INSERT INTO `PAISES` VALUES(115, 'JO', 'JORDANIA');
INSERT INTO `PAISES` VALUES(116, 'KZ', 'KAZAJSTÁN');
INSERT INTO `PAISES` VALUES(117, 'KE', 'KENIA');
INSERT INTO `PAISES` VALUES(118, 'KG', 'KIRGUISTÁN');
INSERT INTO `PAISES` VALUES(119, 'KI', 'KIRIBATI');
INSERT INTO `PAISES` VALUES(120, 'KW', 'KUWAIT');
INSERT INTO `PAISES` VALUES(121, 'LA', 'LAOS');
INSERT INTO `PAISES` VALUES(122, 'LS', 'LESOTHO');
INSERT INTO `PAISES` VALUES(123, 'LV', 'LETONIA');
INSERT INTO `PAISES` VALUES(124, 'LB', 'LÍBANO');
INSERT INTO `PAISES` VALUES(125, 'LR', 'LIBERIA');
INSERT INTO `PAISES` VALUES(126, 'LY', 'LIBIA');
INSERT INTO `PAISES` VALUES(127, 'LI', 'LIECHTENSTEIN');
INSERT INTO `PAISES` VALUES(128, 'LT', 'LITUANIA');
INSERT INTO `PAISES` VALUES(129, 'LU', 'LUXEMBURGO');
INSERT INTO `PAISES` VALUES(130, 'MO', 'MACAO');
INSERT INTO `PAISES` VALUES(131, 'MK', 'ARY MACEDONIA');
INSERT INTO `PAISES` VALUES(132, 'MG', 'MADAGASCAR');
INSERT INTO `PAISES` VALUES(133, 'MY', 'MALASIA');
INSERT INTO `PAISES` VALUES(134, 'MW', 'MALAWI');
INSERT INTO `PAISES` VALUES(135, 'MV', 'MALDIVAS');
INSERT INTO `PAISES` VALUES(136, 'ML', 'MALÍ');
INSERT INTO `PAISES` VALUES(137, 'MT', 'MALTA');
INSERT INTO `PAISES` VALUES(138, 'FK', 'ISLAS MALVINAS');
INSERT INTO `PAISES` VALUES(139, 'MP', 'ISLAS MARIANAS DEL NORTE');
INSERT INTO `PAISES` VALUES(140, 'MA', 'MARRUECOS');
INSERT INTO `PAISES` VALUES(141, 'MH', 'ISLAS MARSHALL');
INSERT INTO `PAISES` VALUES(142, 'MQ', 'MARTINICA');
INSERT INTO `PAISES` VALUES(143, 'MU', 'MAURICIO');
INSERT INTO `PAISES` VALUES(144, 'MR', 'MAURITANIA');
INSERT INTO `PAISES` VALUES(145, 'YT', 'MAYOTTE');
INSERT INTO `PAISES` VALUES(146, 'MX', 'MÉXICO');
INSERT INTO `PAISES` VALUES(147, 'FM', 'MICRONESIA');
INSERT INTO `PAISES` VALUES(148, 'MD', 'MOLDAVIA');
INSERT INTO `PAISES` VALUES(149, 'MC', 'MÓNACO');
INSERT INTO `PAISES` VALUES(150, 'MN', 'MONGOLIA');
INSERT INTO `PAISES` VALUES(151, 'MS', 'MONTSERRAT');
INSERT INTO `PAISES` VALUES(152, 'MZ', 'MOZAMBIQUE');
INSERT INTO `PAISES` VALUES(153, 'MM', 'MYANMAR');
INSERT INTO `PAISES` VALUES(154, 'NA', 'NAMIBIA');
INSERT INTO `PAISES` VALUES(155, 'NR', 'NAURU');
INSERT INTO `PAISES` VALUES(156, 'NP', 'NEPAL');
INSERT INTO `PAISES` VALUES(157, 'NI', 'NICARAGUA');
INSERT INTO `PAISES` VALUES(158, 'NE', 'NÍGER');
INSERT INTO `PAISES` VALUES(159, 'NG', 'NIGERIA');
INSERT INTO `PAISES` VALUES(160, 'NU', 'NIUE');
INSERT INTO `PAISES` VALUES(161, 'NF', 'ISLA NORFOLK');
INSERT INTO `PAISES` VALUES(162, 'NO', 'NORUEGA');
INSERT INTO `PAISES` VALUES(163, 'NC', 'NUEVA CALEDONIA');
INSERT INTO `PAISES` VALUES(164, 'NZ', 'NUEVA ZELANDA');
INSERT INTO `PAISES` VALUES(165, 'OM', 'OMÁN');
INSERT INTO `PAISES` VALUES(166, 'NL', 'PAÍSES BAJOS');
INSERT INTO `PAISES` VALUES(167, 'PK', 'PAKISTÁN');
INSERT INTO `PAISES` VALUES(168, 'PW', 'PALAU');
INSERT INTO `PAISES` VALUES(169, 'PS', 'PALESTINA');
INSERT INTO `PAISES` VALUES(170, 'PA', 'PANAMÁ');
INSERT INTO `PAISES` VALUES(171, 'PG', 'PAPÚA NUEVA GUINEA');
INSERT INTO `PAISES` VALUES(172, 'PY', 'PARAGUAY');
INSERT INTO `PAISES` VALUES(173, 'PE', 'PERÚ');
INSERT INTO `PAISES` VALUES(174, 'PN', 'ISLAS PITCAIRN');
INSERT INTO `PAISES` VALUES(175, 'PF', 'POLINESIA FRANCESA');
INSERT INTO `PAISES` VALUES(176, 'PL', 'POLONIA');
INSERT INTO `PAISES` VALUES(177, 'PT', 'PORTUGAL');
INSERT INTO `PAISES` VALUES(178, 'PR', 'PUERTO RICO');
INSERT INTO `PAISES` VALUES(179, 'QA', 'QATAR');
INSERT INTO `PAISES` VALUES(180, 'GB', 'REINO UNIDO');
INSERT INTO `PAISES` VALUES(181, 'RE', 'REUNIÓN');
INSERT INTO `PAISES` VALUES(182, 'RW', 'RUANDA');
INSERT INTO `PAISES` VALUES(183, 'RO', 'RUMANIA');
INSERT INTO `PAISES` VALUES(184, 'RU', 'RUSIA');
INSERT INTO `PAISES` VALUES(185, 'EH', 'SAHARA OCCIDENTAL');
INSERT INTO `PAISES` VALUES(186, 'SB', 'ISLAS SALOMÓN');
INSERT INTO `PAISES` VALUES(187, 'WS', 'SAMOA');
INSERT INTO `PAISES` VALUES(188, 'AS', 'SAMOA AMERICANA');
INSERT INTO `PAISES` VALUES(189, 'KN', 'SAN CRISTÓBAL Y NEVIS');
INSERT INTO `PAISES` VALUES(190, 'SM', 'SAN MARINO');
INSERT INTO `PAISES` VALUES(191, 'PM', 'SAN PEDRO Y MIQUELÓN');
INSERT INTO `PAISES` VALUES(192, 'VC', 'SAN VICENTE Y LAS GRANADINAS');
INSERT INTO `PAISES` VALUES(193, 'SH', 'SANTA HELENA');
INSERT INTO `PAISES` VALUES(194, 'LC', 'SANTA LUCÍA');
INSERT INTO `PAISES` VALUES(195, 'ST', 'SANTO TOMÉ Y PRÍNCIPE');
INSERT INTO `PAISES` VALUES(196, 'SN', 'SENEGAL');
INSERT INTO `PAISES` VALUES(197, 'CS', 'SERBIA Y MONTENEGRO');
INSERT INTO `PAISES` VALUES(198, 'SC', 'SEYCHELLES');
INSERT INTO `PAISES` VALUES(199, 'SL', 'SIERRA LEONA');
INSERT INTO `PAISES` VALUES(200, 'SG', 'SINGAPUR');
INSERT INTO `PAISES` VALUES(201, 'SY', 'SIRIA');
INSERT INTO `PAISES` VALUES(202, 'SO', 'SOMALIA');
INSERT INTO `PAISES` VALUES(203, 'LK', 'SRI LANKA');
INSERT INTO `PAISES` VALUES(204, 'SZ', 'SUAZILANDIA');
INSERT INTO `PAISES` VALUES(205, 'ZA', 'SUDÁFRICA');
INSERT INTO `PAISES` VALUES(206, 'SD', 'SUDÁN');
INSERT INTO `PAISES` VALUES(207, 'SE', 'SUECIA');
INSERT INTO `PAISES` VALUES(208, 'CH', 'SUIZA');
INSERT INTO `PAISES` VALUES(209, 'SR', 'SURINAM');
INSERT INTO `PAISES` VALUES(210, 'SJ', 'SVALBARD Y JAN MAYEN');
INSERT INTO `PAISES` VALUES(211, 'TH', 'TAILANDIA');
INSERT INTO `PAISES` VALUES(212, 'TW', 'TAIWÁN');
INSERT INTO `PAISES` VALUES(213, 'TZ', 'TANZANIA');
INSERT INTO `PAISES` VALUES(214, 'TJ', 'TAYIKISTÁN');
INSERT INTO `PAISES` VALUES(215, 'IO', 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO');
INSERT INTO `PAISES` VALUES(216, 'TF', 'TERRITORIOS AUSTRALES FRANCESES');
INSERT INTO `PAISES` VALUES(217, 'TL', 'TIMOR ORIENTAL');
INSERT INTO `PAISES` VALUES(218, 'TG', 'TOGO');
INSERT INTO `PAISES` VALUES(219, 'TK', 'TOKELAU');
INSERT INTO `PAISES` VALUES(220, 'TO', 'TONGA');
INSERT INTO `PAISES` VALUES(221, 'TT', 'TRINIDAD Y TOBAGO');
INSERT INTO `PAISES` VALUES(222, 'TN', 'TÚNEZ');
INSERT INTO `PAISES` VALUES(223, 'TC', 'ISLAS TURCAS Y CAICOS');
INSERT INTO `PAISES` VALUES(224, 'TM', 'TURKMENISTÁN');
INSERT INTO `PAISES` VALUES(225, 'TR', 'TURQUÍA');
INSERT INTO `PAISES` VALUES(226, 'TV', 'TUVALU');
INSERT INTO `PAISES` VALUES(227, 'UA', 'UCRANIA');
INSERT INTO `PAISES` VALUES(228, 'UG', 'UGANDA');
INSERT INTO `PAISES` VALUES(229, 'UY', 'URUGUAY');
INSERT INTO `PAISES` VALUES(230, 'UZ', 'UZBEKISTÁN');
INSERT INTO `PAISES` VALUES(231, 'VU', 'VANUATU');
INSERT INTO `PAISES` VALUES(232, 'VE', 'VENEZUELA');
INSERT INTO `PAISES` VALUES(233, 'VN', 'VIETNAM');
INSERT INTO `PAISES` VALUES(234, 'VG', 'ISLAS VÍRGENES BRITÁNICAS');
INSERT INTO `PAISES` VALUES(235, 'VI', 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS');
INSERT INTO `PAISES` VALUES(236, 'WF', 'WALLIS Y FUTUNA');
INSERT INTO `PAISES` VALUES(237, 'YE', 'YEMEN');
INSERT INTO `PAISES` VALUES(238, 'DJ', 'YIBUTI');
INSERT INTO `PAISES` VALUES(239, 'ZM', 'ZAMBIA');
INSERT INTO `PAISES` VALUES(240, 'ZW', 'ZIMBABUE');
