DROP DATABASE IF EXISTS DBPInf;
CREATE DATABASE DBPInf;
use DBPInf;

CREATE TABLE IF NOT EXISTS USUARIO (
	ID_USUARIO INT NOT NULL PRIMARY KEY auto_increment,
	NOMBRE VARCHAR(25) NOT NULL,
	APELLIDOS VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PAIS VARCHAR(25) NOT NULL,
    LOCALIDAD VARCHAR(25) NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    TLF_MOVIL VARCHAR(9) NOT NULL,
	TLF_FIJO VARCHAR(9),	
    NOMBRE_USUARIO VARCHAR(25) NOT NULL,
    CONTRASENA_USUARIO VARCHAR(256) NOT NULL,
    SAL VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASIGNACION (
	ID_ASIGNACION INT NOT NULL PRIMARY KEY auto_increment,
	ID_RESPONSABLE INT NOT NULL,
	ID_USUARIO INT NOT NULL,
    DESCRIPCION VARCHAR(25),
    FOREIGN KEY FK_RESPONSABLE1(ID_RESPONSABLE) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY FK_RESPONSABLE2(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS ROL (
	ID_ROL INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(25) NOT NULL,
	DESCRIPCION VARCHAR(25)
);

/* Tabla relacion n:n entre usuario y rol */
CREATE TABLE IF NOT EXISTS ROLES (
	ID_USUARIO INT NOT NULL,
	ID_ROL INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_ROL),
    FOREIGN KEY FK_ROLES1(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY FK_ROLES2(ID_ROL) REFERENCES ROL(ID_ROL)
);

CREATE TABLE IF NOT EXISTS MEDICIONES (
	ID_MEDICION INT NOT NULL PRIMARY KEY,
	ID_USUARIO INT NOT NULL,
	SENSOR VARCHAR(25) NOT NULL,
	MEDICION VARCHAR(25) NOT NULL,
    FOREIGN KEY FK_MEDICIONES(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS ACCION (
	ID_ACCION INT NOT NULL PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS HISTORICO (
	ID_HISTORICO INT NOT NULL PRIMARY KEY auto_increment,
    ID_USUARIO INT NOT NULL,
	ID_ACCION INT NOT NULL,
	CAMBIO_ANTIGUO VARCHAR(50) NOT NULL,
	CAMBIO_NUEVO VARCHAR(50) NOT NULL,
    FOREIGN KEY FK_HISTORICO1(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY FK_HISTORICO2(ID_ACCION) REFERENCES ACCION(ID_ACCION)
);

CREATE TABLE IF NOT EXISTS `PROVINCIAS` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PROVINCIA` VARCHAR(255) COLLATE UTF8_SPANISH_CI NOT NULL
  PRIMARY KEY (`ID`)
) ENGINE=MYISAM  DEFAULT CHARSET=UTF8 COLLATE=UTF8_SPANISH_CI CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC AUTO_INCREMENT=53 ;

--
-- VOLCADO DE DATOS PARA LA TABLA `PROVINCIAS`
--

INSERT INTO `PROVINCIAS` (`ID`, `PROVINCIA`,) VALUES
(1,'ÁLAVA'),
(2,'ALBACETE'),
(3, 'ALICANTE'),
(4, 'ALMERÍA'),
(5, 'ÁVILA'),
(6, 'BADAJOZ'),
(7, 'ILLES BALEARS'),
(8, 'BARCELONA'),
(9, 'BURGOS'),
(10, 'CÁCERES'),
(11, 'CÁDIZ'),
(12, 'CASTELLÓN'),
(13, 'CIUDAD REAL'),
(14, 'CÓRDOBA'),
(15, 'A CORUÑA'),
(16, 'CUENCA'),
(17, 'GIRONA'),
(18, 'GRANADA'),
(19, 'GUADALAJARA'),
(20, 'GUIPÚZCOA'),
(21, 'HUELVA'),
(22, 'HUESCA'),
(23, 'JAÉN'),
(24, 'LEÓN'),
(25, 'LLEIDA'),
(26, 'LA RIOJA'),
(27, 'LUGO'),
(28, 'MADRID'),
(29, 'MÁLAGA'),
(30, 'MURCIA'),
(31, 'NAVARRA'),
(32, 'OURENSE'),
(33, 'ASTURIAS'),
(34, 'PALENCIA'),
(35, 'LAS PALMAS'),
(36, 'PONTEVEDRA'),
(37, 'SALAMANCA'),
(38, 'SANTA CRUZ DE TENERIFE'),
(39, 'CANTABRIA'),
(40, 'SEGOVIA'),
(41, 'SEVILLA'),
(42, 'SORIA'),
(43, 'TARRAGONA'),
(44, 'TERUEL'),
(45, 'TOLEDO'),
(46, 'VALENCIA'),
(47, 'VALLADOLID'),
(48, 'VIZCAYA'),
(49, 'ZAMORA'),
(50, 'ZARAGOZA'),
(51, 'CEUTA'),
(52, 'MELILLA');
