use DBPInf;

CREATE TABLE IF NOT EXISTS ROLES (
	
    #RELACIONES
    
		#PRIMARY KEY
        
			 ID_ROL INT NOT NULL PRIMARY KEY,
             
    #ATRIBUTOS
			
		NOMBRE VARCHAR(25) NOT NULL,
		DESCRIPCION VARCHAR(100)
);

INSERT INTO ROLES
	(ID_ROL, NOMBRE, DESCRIPCION)
VALUES
	(1,'Administrador', 'Encargado de registrar y editar usuarios de la aplicación'),
    (2,'Medico', 'Encargado sanitario de pacientes, tiene asignados N pacientes'),
    (3,'Familiar', 'Encargado familiar del paciente, tiene asignados N pacientes'),
    (4,'Paciente', 'Paciente, tiene asignado 1 medico y 1 familiar');

CREATE TABLE IF NOT EXISTS USUARIO (
	
    #RELACIONES
    
		ID_ROL INT NOT NULL,
		ID_MUNICIPIO INT,
    
    #ATRIBUTOS
    
		#PRIMARY KEY
        
			DNI VARCHAR(9) PRIMARY KEY,
		
        #CONTRASENA
        
			PASS_HASHED VARCHAR(256) NOT NULL,
			SALT blob NOT NULL,
		
        #RESTO
        
			NOMBRE VARCHAR(25),
			APELLIDOS VARCHAR(25),
			EMAIL VARCHAR(50),
			DIRECCION VARCHAR(50),
			TLF_MOVIL VARCHAR(9),
			TLF_FIJO VARCHAR(9),	  
            
	#CLAVES FORANEAS
    
		FOREIGN KEY FK_ROLES(ID_ROL) REFERENCES ROLES(ID_ROL),
		FOREIGN KEY FK_MUNICIPIO(ID_MUNICIPIO) REFERENCES MUNICIPIOS(ID_MUNICIPIO)
);

CREATE TABLE IF NOT EXISTS TIPO_ASIGNACION (

	#RELACIONES
    
		#PRIMARY KEY
        
			ID_TIPO INT NOT NULL PRIMARY KEY,
    
	#ATRIBUTOS
        
		DESCRIPCION VARCHAR(50)
);

INSERT INTO TIPO_ASIGNACION
	(ID_TIPO, DESCRIPCION)
VALUES
	(1,'Medico - Paciente / Paciente - Medico'),
    (2,'Familiar - Paciente / Paciente - Familiar');


CREATE TABLE IF NOT EXISTS ASIGNACION (
	
    #RELACIONES
    
		#USUARIO
        
			DNI_ASOCIADO VARCHAR(9) NOT NULL,
			DNI_ASIGNADO VARCHAR(9) NOT NULL,			
        
        #TIPO DE ASIGNACION
        
			ID_TIPO INT NOT NULL,
        
	#ATRIBUTOS
    
		DESCRIPCION VARCHAR(25),
        
    #CLAVES FORANEAS
    
		FOREIGN KEY FK_RESPONSABLE1(DNI_ASIGNADO) REFERENCES USUARIO(DNI),
		FOREIGN KEY FK_RESPONSABLE2(DNI_ASOCIADO) REFERENCES USUARIO(DNI),
		FOREIGN KEY FK_TIPO1(ID_TIPO) REFERENCES TIPO_ASIGNACION(ID_TIPO)
);

CREATE TABLE IF NOT EXISTS MENSAJERIA (
	
    #RELACIONES
    
		DNI_EMISOR VARCHAR(9) NOT NULL,
		DNI_RECEPTOR VARCHAR(9) NOT NULL,
        
	#ATRIBUTOS
    
		LEIDO BOOL NOT NULL,
		ASUNTO VARCHAR(100),
		MENSAJE VARCHAR(2500),
        
	#CLAVES FORANEAS
    
		FOREIGN KEY FK_EMISOR(DNI_EMISOR) REFERENCES USUARIO(DNI),
		FOREIGN KEY FK_RECEPTOR(DNI_RECEPTOR) REFERENCES USUARIO(DNI)
);

CREATE TABLE IF NOT EXISTS SENSOR_RITMO_CARDIACO (
	
    #RELACIONES
		
        DNI_PACIENTE VARCHAR(9) NOT NULL,
        
	#ATRIBUTOS
        
		VALOR INT NOT NULL,
        FECHA DATETIME NOT NULL,
            
	#CLAVES FORANEAS
    
		FOREIGN KEY FK_RITMO_CARDIACO(DNI_PACIENTE) REFERENCES USUARIO(DNI)
);

CREATE TABLE IF NOT EXISTS SENSOR_PUERTA_CALLE (
	
    #RELACIONES
		
        DNI_PACIENTE VARCHAR(9) NOT NULL,
        
	#ATRIBUTOS
        
		ABIERTA BOOLEAN NOT NULL,
        FECHA DATETIME NOT NULL,
            
	#CLAVES FORANEAS
    
		FOREIGN KEY FK_RITMO_CARDIACO(DNI_PACIENTE) REFERENCES USUARIO(DNI)
);

CREATE TABLE IF NOT EXISTS TIPO_PRESENCIA(
	
    #RELACIONES
    
		#PRIMARY KEY
			
            ID_PRESENCIA INT NOT NULL PRIMARY KEY,
	
    #ATRIBUTOS    
		
		LUGAR VARCHAR(50) NOT NULL
);

INSERT INTO TIPO_PRESENCIA 
	VALUES
    (1,'Salón'),
    (2,'Cocina'),
    (3,'Habitación');

CREATE TABLE IF NOT EXISTS SENSOR_PRESENCIA (
	
    #RELACIONES
		
        DNI_PACIENTE VARCHAR(9) NOT NULL,
		ID_TIPO_PRESENCIA INT NOT NULL,
        
	#ATRIBUTOS
        
        FECHA DATETIME NOT NULL,
            
	#CLAVES FORANEAS
    
		FOREIGN KEY FK_RITMO_CARDIACO(DNI_PACIENTE) REFERENCES USUARIO(DNI),
        FOREIGN KEY FK_TIPO_PRESENCIA(ID_TIPO_PRESENCIA) REFERENCES TIPO_PRESENCIA(ID_PRESENCIA)
);



/* Aun no esta claro
CREATE TABLE IF NOT EXISTS ACCION (
	ID_ACCION INT NOT NULL PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS HISTORICO (
	ID_HISTORICO INT NOT NULL PRIMARY KEY auto_increment,
    ID_USUARIO INT NOT NULL,
	ID_ACCION INT NOT NULL,
	CAMBIO_ANTIGUO VARCHAR(50) NOT NULL,
	CAMBIO_NUEVO VARCHAR(50) NOT NULL,
    FOREIGN KEY FK_HISTORICO1(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY FK_HISTORICO2(ID_ACCION) REFERENCES ACCION(ID_ACCION)
);
*/



 
