/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pinfui.interfaz;

import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pinfui.entidades.Mensaje;
import pinfui.entidades.Usuario;

/**
 *
 * @author Usuario DAM
 */
public class JPanelMensajeria1 extends PlantillaJPanel {
    
    private DefaultTableModel model;
    private Usuario usuario;

    /**
     * Creates new form JPanelMensajeria1
     */
    public JPanelMensajeria1(Usuario usuario) {
        initComponents();
        usuario = this.usuario;
        crearTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearTabla(){
        final String [] nombreColumnas = {"Remitente","Título"};
        
        Object [][] listaRegistrosPP = {};
        
        model = new javax.swing.table.DefaultTableModel(listaRegistrosPP, nombreColumnas)
                {
        	public boolean isCellEditable(int row, int column)
            {
              return false;//This causes all cells to be not editable
            }};
        cargarListaRegistros();
        jTable2.setModel(model);
        
    }
    
    private void cargarListaRegistros(){
        
        for(Mensaje mensaje : usuario.getListaMensajes()){
            Object [] mensajito = {
                mensaje.getEnviadoPor(), mensaje.getTitulo()
            };
            model.addRow(mensajito);
        }
    }
    
    private javax.swing.JTable jTable1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
