/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pinfui.interfaz;

import java.awt.Checkbox;
import java.util.ArrayList;
import javax.swing.JFrame;
import pinfui.controller.GestorDatos;
import pinfui.dto.EstiloCabeceraJTable;
import pinfui.dto.EstiloCotenidoJTable;
import pinfui.dto.Item;
import pinfui.dto.LabelDTO;
import pinfui.entidades.Mensaje;
import pinfui.entidades.Usuario;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import pinfui.entidades.Asignacion;
import pinfui.entidades.Etiqueta;

/**
 *
 * @author Usuario DAM
 */
public class JPanelMensajeriaNuevo extends PlantillaJPanel {

    private Usuario usuario;
    private Mensaje mensaje;
    private DefaultTableModel model;
    private ArrayList<Etiqueta> listaEtiquetas;
    
    /**
     * Creates new form JPanelMensajeVisor
     */
    public JPanelMensajeriaNuevo(Usuario usuario, Mensaje mensaje) {
        initComponents();
        buttonEnviar
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/enviar.png")));
        
        this.usuario = usuario;
        this.mensaje = mensaje;
        visibleToAll(true);
        mensajeToVista();
        
        listaLabels.add(new LabelDTO(labelTitulo, "tituloNuevoMensaje", labelTitulo.getFont().getSize()));
        listaLabels.add(new LabelDTO(jLabel1, "enviarA", jLabel1.getFont().getSize()));
        listaLabels.add(new LabelDTO(jLabel2, "titulo", jLabel2.getFont().getSize()));
        listaLabels.add(new LabelDTO(jLabel3, "etiqueta", jLabel3.getFont().getSize()));
        
        cargarTablaUsuarios();
        
        cargarEtiquetas();
        
        cambiarFuentes();
    }
    
    private void visibleToAll(boolean visible){
        
        jTFTitulo.setVisible(visible);
        jTextArea1.setVisible(visible);
    }
    
    private void mensajeToVista(){
        
        jTFTitulo.setText(mensaje.getAsunto());
        jTextArea1.setText(mensaje.getMensaje());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCBEtiqueta = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonEnviar = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1336, 776));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Enviar a");

        jLabel3.setText("Etiqueta");

        jCBEtiqueta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCBEtiqueta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCBEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEtiquetaActionPerformed(evt);
            }
        });

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jCBEtiqueta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Título");

        jTFTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTituloActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
                    .addComponent(jTFTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        buttonEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/es_ES/enviar.png"))); // NOI18N
        buttonEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEnviarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEnviarMouseExited(evt);
            }
        });

        labelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 153, 255));
        labelTitulo.setText("Nuevo mensaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(buttonEnviar)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEnviar)
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCBEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEtiquetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBEtiquetaActionPerformed

    private void buttonEnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnviarMouseEntered
        buttonEnviar
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/enviar_hover.png")));
    }//GEN-LAST:event_buttonEnviarMouseEntered

    private void buttonEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnviarMouseExited
        buttonEnviar
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/enviar.png")));
    }//GEN-LAST:event_buttonEnviarMouseExited

    private void jTFTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTituloActionPerformed

    private void buttonEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnviarMouseClicked
        enviarMensaje();
    }//GEN-LAST:event_buttonEnviarMouseClicked

    private void cargarTablaUsuarios(){
        jTableUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        jTableUsuarios.getTableHeader().setDefaultRenderer(new EstiloCabeceraJTable());
        jTableUsuarios.setDefaultRenderer(Object.class, new EstiloCotenidoJTable());
        
        final String [] nombreColumnas = {"DNI","Nombre"};
        Object [][] listaRegistrosPP = {};
        model = new javax.swing.table.DefaultTableModel(listaRegistrosPP, nombreColumnas)
                {
        	public boolean isCellEditable(int row, int column)
            {
              return false;//This causes all cells to be not editable
            }};
        referidosToModel(cargarUsuariosReferidos());
        jTableUsuarios.setModel(model);
    }
    
    private void referidosToModel(ArrayList<Usuario> usuarios){
        for (Usuario usuario : usuarios){
            Object [] user = {
                usuario.getDni(), usuario.getNombre()
            };
            model.addRow(user);
        }
    }
    
    private ArrayList<Usuario> cargarUsuariosReferidos(){
        ArrayList<Usuario> usuarios = new ArrayList<>();
        for(Asignacion asig : usuario.getListaAsignacion()){
            if(asig.getUsuarioAsignado() != null){
               usuarios.add(asig.getUsuarioAsignado()); 
            }
            if(asig.getUsuarioAsociado() != null){
               usuarios.add(asig.getUsuarioAsociado()); 
            }
        }
        return usuarios;
    }
    
    private void cargarEtiquetas(){
        ArrayList<Etiqueta> etiquetas = new ArrayList<>();
        ArrayList<String> eti = new ArrayList<>();
        for (Etiqueta etiq : PInfUI.gestorDatos.getEtiquetas()){
            etiquetas.add(etiq);
            eti.add(etiq.getEtiqueta());
        }
        listaEtiquetas = etiquetas;
        String [] etiquetaValores = eti.toArray(new String[eti.size()]);
        jCBEtiqueta = new JComboBox(etiquetaValores);
    }
    
    private void enviarMensaje(){
        String titulo = jTFTitulo.getText();
        String contenido = "¬¬¬ " + usuario.getNombre() + " ¬¬¬\n"
                + jTextArea1.getText();
        String etiqeta = (String) jCBEtiqueta.getSelectedItem();
        String receptores = "";
        for(int x = 0; x < jTableUsuarios.getSelectedRows().length; x++){
            int idTabla = jTableUsuarios.getSelectedRows()[x];
            receptores += (String)jTableUsuarios.getValueAt(idTabla, 0);
            if(x != jTableUsuarios.getSelectedRows().length - 1){
                receptores += "|";
            }
        }
        
        mensaje = new Mensaje(usuario.getDni(), receptores, "asunto", contenido, false, etiqeta);
        GestorDatos.guardarMensaje(mensaje);
    }
    
    public Mensaje getMensaje() {
        return mensaje;
    }

    public void setMensaje(Mensaje mensaje) {
        this.mensaje = mensaje;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonEnviar;
    private javax.swing.JComboBox<Item> jCBEtiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFTitulo;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
