/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pinfui.interfaz;

import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;

import pinfui.controller.LogInController;
import pinfui.dto.ConstantesAplicacion;
import pinfui.dto.Idioma;
import pinfui.dto.Item;
import pinfui.dto.ItemRenderer;
import pinfui.dto.LabelDTO;
import pinfui.dto.TipoVentana;
import pinfui.entidades.Usuario;

/**
 * Pantalla de logeo de usuarios
 *
 * @author ITCOM
 */
public class LogIn extends javax.swing.JFrame {

    private LogInController controlador = new LogInController();

    private boolean terminarHiloButton = false;

    private List<LabelDTO> historicoFuentes;

    /**
     * Constructor
     */
    public LogIn() {
        initComponents();
        generarHistoricoFuentes();
        
        
        //Cargar combo
//        0, 2, 4, 6, 8
        comboSize.addItem(new Item("0", "0"));  
        comboSize.addItem(new Item("2", "2")); 
        comboSize.addItem(new Item("4", "4")); 
        comboSize.addItem(new Item("6", "6")); 
        comboSize.addItem(new Item("8", "8")); 
        
        //Estilo para el combo
        comboSize.setRenderer( new ItemRenderer() );
        
        cambiarFuentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogIn = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelTitulo2 = new javax.swing.JLabel();
        jTFUser = new javax.swing.JTextField();
        labelTitulo3 = new javax.swing.JLabel();
        jPFPass = new javax.swing.JPasswordField();
        comboSize = new javax.swing.JComboBox<>();
        labelTitulo4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        etiquetaButtonDeslizante = new javax.swing.JLabel();
        imagenButtonDeslizante = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        iconSpain = new javax.swing.JLabel();
        iconUSA = new javax.swing.JLabel();
        labelTitulo5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanelLogIn.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelTitulo1.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo1.setForeground(new java.awt.Color(0, 153, 255));
        labelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo1.setText("Introduce tu usuario y contraseña");

        labelTitulo2.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo2.setForeground(new java.awt.Color(0, 153, 255));
        labelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo2.setText("Dni");

        jTFUser.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode()==KeyEvent.VK_ENTER){
                    logIn();
                }
            }
        });

        labelTitulo3.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo3.setForeground(new java.awt.Color(0, 153, 255));
        labelTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo3.setText("Contraseña");

        jPFPass.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode()==KeyEvent.VK_ENTER){
                    logIn();
                }
            }
        });

        comboSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSizeItemStateChanged(evt);
            }
        });

        labelTitulo4.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo4.setForeground(new java.awt.Color(0, 153, 255));
        labelTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo4.setText("Tamaño de letra");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        etiquetaButtonDeslizante.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etiquetaButtonDeslizante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaButtonDeslizante.setText("Acceder");
        etiquetaButtonDeslizante.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        imagenButtonDeslizante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenButtonDeslizante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/submit.png"))); // NOI18N
        imagenButtonDeslizante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagenButtonDeslizante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenButtonDeslizanteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imagenButtonDeslizanteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imagenButtonDeslizanteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(etiquetaButtonDeslizante, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(imagenButtonDeslizante)
                    .addContainerGap(116, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(etiquetaButtonDeslizante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(imagenButtonDeslizante)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        iconSpain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/flag_spain.png"))); // NOI18N
        iconSpain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconSpain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconSpainMouseClicked(evt);
            }
        });

        iconUSA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/flag_usa.png"))); // NOI18N
        iconUSA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconUSA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconUSAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(iconSpain)
                .addGap(77, 77, 77)
                .addComponent(iconUSA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconUSA)
                    .addComponent(iconSpain))
                .addContainerGap())
        );

        labelTitulo5.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo5.setForeground(new java.awt.Color(0, 153, 255));
        labelTitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo5.setText("Seleccionar idioma");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPFPass)
            .addComponent(jTFUser)
            .addComponent(labelTitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(labelTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comboSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelTitulo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelTitulo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelTitulo1)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTitulo2)
                .addGap(11, 11, 11)
                .addComponent(jTFUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTitulo3)
                .addGap(11, 11, 11)
                .addComponent(jPFPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTitulo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(labelTitulo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLogInLayout = new javax.swing.GroupLayout(jPanelLogIn);
        jPanelLogIn.setLayout(jPanelLogInLayout);
        jPanelLogInLayout.setHorizontalGroup(
            jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLogInLayout.setVerticalGroup(
            jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLogInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconSpainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconSpainMouseClicked
        PInfUI.cambiarIdioma(Idioma.CASTELLANO);
        cambiarFuentes();
    }//GEN-LAST:event_iconSpainMouseClicked

    private void iconUSAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconUSAMouseClicked
        PInfUI.cambiarIdioma(Idioma.INGLES);
        cambiarFuentes();
    }//GEN-LAST:event_iconUSAMouseClicked


    /**
     * Metodo que cambia el tamaño de fuentes al elegir un numero en el
     * JComboBox
     *
     * @param evt
     */
    private void comboSizeItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboSizeItemStateChanged
        cambiarFuentes();
    }// GEN-LAST:event_comboSizeItemStateChanged

    private void imagenButtonDeslizanteMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_imagenButtonDeslizanteMouseExited
        terminarHiloButton = true;
        imagenButtonDeslizante
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/submit.png")));
    }// GEN-LAST:event_imagenButtonDeslizanteMouseExited

    private void imagenButtonDeslizanteMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_imagenButtonDeslizanteMouseEntered
        terminarHiloButton = false;

        crearHiloCambioIconButton();
    }// GEN-LAST:event_imagenButtonDeslizanteMouseEntered

    /**
     * Accion de log in
     * Es llamada por listener de keys y por el boton de login
     */
    private void logIn()
    {
        Usuario usuario = null;
//            usuario = PInfUI.gestorDatos.login("14569823X", "123456789");
        usuario = PInfUI.gestorDatos.login(jTFUser.getText(), jPFPass.getText());

        if (usuario != null) {
            if (usuario.getId_Rol() == ConstantesAplicacion.ROL_ADMIN) {
                PInfUI.abrirVentana(usuario, this, TipoVentana.ADMIN);
            } else if (usuario.getId_Rol() == ConstantesAplicacion.ROL_MEDICO) {
                PInfUI.abrirVentana(usuario, this, TipoVentana.MEDICO);
            } else if (usuario.getId_Rol() == ConstantesAplicacion.ROL_FAMILIAR) {
                PInfUI.abrirVentana(usuario, this, TipoVentana.FAMILIAR);
            } else if (usuario.getId_Rol() == ConstantesAplicacion.ROL_PACIENTE) {
                PInfUI.abrirVentana(usuario, this, TipoVentana.PACIENTE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "La combinación Usuario - Contraseña es incorrecta, prueba de nuevo",
                    "Error", ERROR_MESSAGE);
        }
    }
    
    /**
     * Handler boton login
     * @param evt 
     */
    private void imagenButtonDeslizanteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_imagenButtonDeslizanteMouseClicked
        logIn();
    }// GEN-LAST:event_imagenButtonDeslizanteMouseClicked

    /**
     * Metodo encargado de rellenar la lista de JLabels que tiene la pantalla
     * para el cambio de tamaños
     */
    private void generarHistoricoFuentes() {
        historicoFuentes = new ArrayList<LabelDTO>();
        historicoFuentes.add(new LabelDTO(labelTitulo1, "tituloLogin", labelTitulo1.getFont().getSize()));
        historicoFuentes.add(new LabelDTO(labelTitulo2, "dni", labelTitulo2.getFont().getSize()));
        historicoFuentes.add(new LabelDTO(labelTitulo3, "password", labelTitulo3.getFont().getSize()));
        historicoFuentes.add(new LabelDTO(labelTitulo4, "sizeLetra", labelTitulo4.getFont().getSize()));
        historicoFuentes.add(new LabelDTO(etiquetaButtonDeslizante, "botonAcceder", etiquetaButtonDeslizante.getFont().getSize()));
        historicoFuentes.add(new LabelDTO(labelTitulo5, "cambiarIdioma", labelTitulo5.getFont().getSize()));
        
    }

    /**
     * Creacion de un hilo en segundo plano encargado de modificar la imagen de
     * los botones deslizantes
     *
     * @param imagenButtonDeslizante JLabel al que se le cambiara la imagen
     */
    protected void crearHiloCambioIconButton() {
        // Creacion de un hilo para cambiar la imagen del correo cuando tengas
        // notificaciones nuevas - Asi llama mas la atencion
        new Thread(new Runnable() {
            public void run() {

                // Se controlara el tiempo para que cambie el icono cada segundo
                Calendar proximaEjecucion = Calendar.getInstance();
                proximaEjecucion.setTime(new java.util.Date());
                proximaEjecucion.add(Calendar.MILLISECOND, 5);

                int contador = 1;
                // Siempre que terminarHiloCorreo este a false se ejecutara el hilo
                while (!terminarHiloButton && contador < 19) {
                    Calendar fechaActual = Calendar.getInstance();
                    fechaActual.setTime(new java.util.Date());

                    if (fechaActual.compareTo(proximaEjecucion) >= 0) {
                        imagenButtonDeslizante.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/resources/images/submit" + contador + ".png")));
                        contador++;
                        proximaEjecucion.setTime(new java.util.Date());
                        proximaEjecucion.add(Calendar.MILLISECOND, 5);
                    }

                    try {
                        java.lang.Thread.sleep(100);
                    } catch (Exception e) {
                    }
                }

                if (contador == 19) {
                    imagenButtonDeslizante.setIcon(
                            new javax.swing.ImageIcon(getClass().getResource("/resources/images/submit19.png")));
                }
            }
        }).start();
    }

    /**
     * Metodo encargado de cambiar las fuentes de la lista de labels que tiene
     * una pantalla
     */
    private void cambiarFuentes() {

        int size = Integer.parseInt(comboSize.getSelectedItem().toString());
        PInfUI.setSizeFuente(size);

        for (LabelDTO label : historicoFuentes) {
            label.getLabel().setFont(cambiarSize(label.getSize(), size));
            label.getLabel().setText(PInfUI.getBundle().getString(label.getIdTexto()));
        }

    }

    /**
     * Metodo especifico para cambiar el tamaño de una fuente
     *
     * @param style Tipo de estilo, negrita, cursiva, etc
     * @param sizeActual Tamaño que tiene actualmente la fuente
     * @param suma Cantidad que se quiere agrandar el tamaño de la fuente actual
     * @return Devuelve una fuente con el tamaño cambiado
     */
    private java.awt.Font cambiarSize(int sizeActual, int suma) {
        return new java.awt.Font("Tahoma", 0, sizeActual + suma);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Item> comboSize;
    private javax.swing.JLabel etiquetaButtonDeslizante;
    private javax.swing.JLabel iconSpain;
    private javax.swing.JLabel iconUSA;
    private javax.swing.JLabel imagenButtonDeslizante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPFPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelLogIn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFUser;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JLabel labelTitulo3;
    private javax.swing.JLabel labelTitulo4;
    private javax.swing.JLabel labelTitulo5;
    // End of variables declaration//GEN-END:variables
}
