/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pinfui.interfaz;

import java.sql.SQLException;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import pinfui.controller.LogInController;
import pinfui.dto.ConstantesAplicacion;
import pinfui.dto.LabelDTO;
import pinfui.dto.TipoVentana;
import pinfui.entidades.Asignacion;
import pinfui.entidades.Usuario;

/**
 * Pantalla de logeo de usuarios
 *
 * @author ITCOM
 */
public class LogIn extends javax.swing.JFrame {

    private LogInController controlador = new LogInController();

    private boolean terminarHiloButton = false;

    private List<LabelDTO> historicoFuentes;

    /**
     * Constructor
     */
    public LogIn() {
        initComponents();
        generarHistoricoFuentes();
        cambiarFuentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jPFPass = new javax.swing.JPasswordField();
		jTFUser = new javax.swing.JTextField();
		jLabelRegistro = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		labelTitulo1 = new javax.swing.JLabel();
		labelTitulo4 = new javax.swing.JLabel();
		labelTitulo2 = new javax.swing.JLabel();
		panelButtonDeslizante = new javax.swing.JPanel();
		etiquetaButtonDeslizante = new javax.swing.JLabel();
		imagenButtonDeslizante = new javax.swing.JLabel();
		comboSize = new javax.swing.JComboBox<>();
		labelTitulo3 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox<>();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabelRegistro.setForeground(new java.awt.Color(51, 51, 255));
		jLabelRegistro.setText("Aun no estas registrado? Haz click");
		jLabelRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabelRegistroMouseClicked(evt);
			}
		});

		labelTitulo1.setBackground(new java.awt.Color(255, 255, 255));
		labelTitulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		labelTitulo1.setForeground(new java.awt.Color(0, 153, 255));
		labelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelTitulo1.setText("Introduce tu usuario y contraseña");

		labelTitulo4.setBackground(new java.awt.Color(255, 255, 255));
		labelTitulo4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		labelTitulo4.setForeground(new java.awt.Color(0, 153, 255));
		labelTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelTitulo4.setText("Tamaño de letra");

		labelTitulo2.setBackground(new java.awt.Color(255, 255, 255));
		labelTitulo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		labelTitulo2.setForeground(new java.awt.Color(0, 153, 255));
		labelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelTitulo2.setText("Dni");

		panelButtonDeslizante.setBackground(new java.awt.Color(255, 255, 255));
		panelButtonDeslizante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		panelButtonDeslizante.setLayout(null);

		etiquetaButtonDeslizante.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		etiquetaButtonDeslizante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		etiquetaButtonDeslizante.setText("Acceder");
		panelButtonDeslizante.add(etiquetaButtonDeslizante);
		etiquetaButtonDeslizante.setBounds(0, 1, 370, 30);

		imagenButtonDeslizante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		imagenButtonDeslizante
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/submit.png"))); // NOI18N
		imagenButtonDeslizante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		imagenButtonDeslizante.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				imagenButtonDeslizanteMouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				imagenButtonDeslizanteMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				imagenButtonDeslizanteMouseExited(evt);
			}
		});
		panelButtonDeslizante.add(imagenButtonDeslizante);
		imagenButtonDeslizante.setBounds(0, 0, 370, 35);

		comboSize.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "0", "2", "4", "6", "8", "10", "12", "14", "16" }));
		comboSize.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				comboSizeItemStateChanged(evt);
			}
		});

		labelTitulo3.setBackground(new java.awt.Color(255, 255, 255));
		labelTitulo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		labelTitulo3.setForeground(new java.awt.Color(0, 153, 255));
		labelTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelTitulo3.setText("Contraseña");

		jLabel1.setText("Acceder");

		jComboBox1.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(labelTitulo3, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(labelTitulo2, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jSeparator1).addComponent(jTFUser)
				.addComponent(labelTitulo1, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPFPass)
				.addComponent(labelTitulo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(comboSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(159, 159, 159).addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(78, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE,
														240, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(54, 54, 54))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(22, 22, 22))))
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
						panelButtonDeslizante, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(26, 26, 26)
						.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(43, 43, 43).addComponent(labelTitulo1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(labelTitulo2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jTFUser, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(labelTitulo3)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jPFPass, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
						.addComponent(labelTitulo4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(comboSize, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabelRegistro).addContainerGap())
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(343, 343, 343)
								.addComponent(panelButtonDeslizante, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(108, Short.MAX_VALUE))));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

    private void jLabelRegistroMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelRegistroMouseClicked
        PInfUI.abrirVentana(null, this, TipoVentana.REGISTRO);
    }// GEN-LAST:event_jLabelRegistroMouseClicked

    /**
     * Metodo que cambia el tamaño de fuentes al elegir un numero en el
     * JComboBox
     *
     * @param evt
     */
    private void comboSizeItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboSizeItemStateChanged
        cambiarFuentes();
    }// GEN-LAST:event_comboSizeItemStateChanged

    private void imagenButtonDeslizanteMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_imagenButtonDeslizanteMouseExited
        terminarHiloButton = true;
        imagenButtonDeslizante
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/submit.png")));
    }// GEN-LAST:event_imagenButtonDeslizanteMouseExited

    private void imagenButtonDeslizanteMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_imagenButtonDeslizanteMouseEntered
        terminarHiloButton = false;

        crearHiloCambioIconButton();
    }// GEN-LAST:event_imagenButtonDeslizanteMouseEntered

    /**
     * Accion de logeo para el boton de la pantalla - Abre una ventana diferente
     * segun el rol del usuario logeado
     *
     * @param evt
     */
    private void imagenButtonDeslizanteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_imagenButtonDeslizanteMouseClicked
        Usuario usuario = null;
        try {
            usuario = PInfUI.gestorDatos.login("14569823X", "123456789");
//            usuario = PInfUI.gestorDatos.login(jTFUser.getText(), jPFPass.getText());
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (usuario != null) {
            if (usuario.getId_Rol() == ConstantesAplicacion.ROL_ADMIN) {
                PInfUI.abrirVentana(usuario, this, TipoVentana.REGISTRO);
            } else if (usuario.getId_Rol() == ConstantesAplicacion.ROL_MEDICO) {
                PInfUI.abrirVentana(usuario, this, TipoVentana.MEDICO);
            } else if (usuario.getId_Rol() == ConstantesAplicacion.ROL_FAMILIAR) {
                PInfUI.abrirVentana(usuario, this, TipoVentana.FAMILIAR);
            } else if (usuario.getId_Rol() == ConstantesAplicacion.ROL_PACIENTE) {
                PInfUI.abrirVentana(usuario, this, TipoVentana.PACIENTE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "La combinación Usuario - Contraseña es incorrecta, prueba de nuevo",
                    "Error", ERROR_MESSAGE);
        }

    }// GEN-LAST:event_imagenButtonDeslizanteMouseClicked

    /**
     * Metodo encargado de rellenar la lista de JLabels que tiene la pantalla
     * para el cambio de tamaños
     */
    private void generarHistoricoFuentes() {
        historicoFuentes = new ArrayList<LabelDTO>();
        historicoFuentes.add(new LabelDTO(labelTitulo1, "tituloLogin", labelTitulo1.getFont().getSize()));
        historicoFuentes.add(new LabelDTO(labelTitulo2, "dni", labelTitulo2.getFont().getSize()));
        historicoFuentes.add(new LabelDTO(labelTitulo3, "password", labelTitulo3.getFont().getSize()));
        historicoFuentes.add(new LabelDTO(labelTitulo4, "sizeLetra", labelTitulo4.getFont().getSize()));
        historicoFuentes.add(new LabelDTO(etiquetaButtonDeslizante, "botonAcceder", etiquetaButtonDeslizante.getFont().getSize()));
    }

    /**
     * Creacion de un hilo en segundo plano encargado de modificar la imagen de
     * los botones deslizantes
     *
     * @param imagenButtonDeslizante JLabel al que se le cambiara la imagen
     */
    private void crearHiloCambioIconButton() {
        // Creacion de un hilo para cambiar la imagen del correo cuando tengas
        // notificaciones nuevas - Asi llama mas la atencion
        new Thread(new Runnable() {
            public void run() {

                // Se controlara el tiempo para que cambie el icono cada segundo
                Calendar proximaEjecucion = Calendar.getInstance();
                proximaEjecucion.setTime(new java.util.Date());
                proximaEjecucion.add(Calendar.MILLISECOND, 5);

                int contador = 1;
                // Siempre que terminarHiloCorreo este a false se ejecutara el hilo
                while (!terminarHiloButton && contador < 19) {
                    Calendar fechaActual = Calendar.getInstance();
                    fechaActual.setTime(new java.util.Date());

                    if (fechaActual.compareTo(proximaEjecucion) >= 0) {
                        imagenButtonDeslizante.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/resources/images/submit" + contador + ".png")));
                        contador++;
                        proximaEjecucion.setTime(new java.util.Date());
                        proximaEjecucion.add(Calendar.MILLISECOND, 5);
                    }

                    try {
                        java.lang.Thread.sleep(100);
                    } catch (Exception e) {
                    }
                }

                if (contador == 19) {
                    imagenButtonDeslizante.setIcon(
                            new javax.swing.ImageIcon(getClass().getResource("/resources/images/submit19.png")));
                }
            }
        }).start();
    }

    /**
     * Metodo encargado de cambiar las fuentes de la lista de labels que tiene
     * una pantalla
     */
    private void cambiarFuentes() {

        int size = Integer.parseInt(comboSize.getSelectedItem().toString());
        PInfUI.setSizeFuente(size);

        for (LabelDTO label : historicoFuentes) {
            label.getLabel().setFont(cambiarSize(label.getSize(), size));
            label.getLabel().setText(PInfUI.getBundle().getString(label.getIdTexto()));
        }

    }

    /**
     * Metodo especifico para cambiar el tamaño de una fuente
     *
     * @param style Tipo de estilo, negrita, cursiva, etc
     * @param sizeActual Tamaño que tiene actualmente la fuente
     * @param suma Cantidad que se quiere agrandar el tamaño de la fuente actual
     * @return Devuelve una fuente con el tamaño cambiado
     */
    private java.awt.Font cambiarSize(int sizeActual, int suma) {
        return new java.awt.Font("Tahoma", 0, sizeActual + suma);
    }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox<String> comboSize;
	private javax.swing.JLabel etiquetaButtonDeslizante;
	private javax.swing.JLabel imagenButtonDeslizante;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelRegistro;
	private javax.swing.JPasswordField jPFPass;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField jTFUser;
	private javax.swing.JLabel labelTitulo1;
	private javax.swing.JLabel labelTitulo2;
	private javax.swing.JLabel labelTitulo3;
	private javax.swing.JLabel labelTitulo4;
	private javax.swing.JPanel panelButtonDeslizante;
	// End of variables declaration//GEN-END:variables
}
