/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pinfui.interfaz;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jdatepicker.DatePicker;
import org.jdatepicker.JDatePicker;
import pinfui.dto.LabelDTO;
import pinfui.dto.TipoSensor;
import pinfui.dto.TipoVentana;
import pinfui.entidades.Asignacion;
import pinfui.entidades.Usuario;

/**
 * Plantilla para las ventanas de diferentes roles
 * @author ITCOM
 */
public class PantallaFamiliar extends PlantillaPantallas {    
    
    private String dniPaciente;
	private String nombrePaciente;
	
	DatePicker picker = new JDatePicker();
        private TipoSensor tipoSensor;
    
	/**
	 * Creates new form PantallaUsuario
	 * @param usuario Usuario logeado
	 */
    public PantallaFamiliar(Usuario usuario) {
        super(usuario);
    	initComponents();
        myInitComponents();
        
        //Handler de salida de la ventana
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);        
        this.addWindowListener(new WindowAdapter() {
            
            @Override
            public void windowClosing(WindowEvent e) {
                int choose = JOptionPane.showConfirmDialog(null,
                        "Seguro que quiere cerrar el programa ?",
                        "Salida", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (choose == JOptionPane.YES_OPTION) {
                    System.exit(0);
                    //PInfUI.abrirVentana(null, null, TipoVentana.LOGIN);
                    System.out.println("close");
                  
                } else {
                    System.out.println("do nothing");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentana = new javax.swing.JPanel();
        panelBarraIzquierda = new javax.swing.JPanel();
        panelUsuario = new javax.swing.JPanel();
        labelNombreUser = new javax.swing.JLabel();
        iconSalir = new javax.swing.JLabel();
        panelOtrasVentanas = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        panelMenuInicio = new javax.swing.JPanel();
        labelMenuInicio = new javax.swing.JLabel();
        imagenMenuInicio = new javax.swing.JLabel();
        panelMenuCardiaco = new javax.swing.JPanel();
        labelMenuCardiaco = new javax.swing.JLabel();
        imagenMenuCardiaco = new javax.swing.JLabel();
        panelMenuPresencia = new javax.swing.JPanel();
        labelMenuPresencia = new javax.swing.JLabel();
        imagenMenuPresencia = new javax.swing.JLabel();
        panelMenuDetectorPuerta = new javax.swing.JPanel();
        labelMenuDetectorPuerta = new javax.swing.JLabel();
        imagenMenuPuerta = new javax.swing.JLabel();
        panelMenuMensajeria = new javax.swing.JPanel();
        imagenMenuMensajeria = new javax.swing.JLabel();
        labelMenuMensajeria = new javax.swing.JLabel();
        iconCorreo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelDatosVentana = new javax.swing.JPanel();
        panelVentanaMensajeria = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        labelTituloVentana = new javax.swing.JLabel();
        panelSensores = new javax.swing.JPanel();
        panelPacientes = new javax.swing.JPanel();
        panelFrameSensor = new javax.swing.JPanel();
        labelTituloSensores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1375, 1000));

        panelVentana.setBackground(new java.awt.Color(255, 255, 255));

        panelBarraIzquierda.setBackground(new java.awt.Color(0, 153, 255));
        panelBarraIzquierda.setPreferredSize(new java.awt.Dimension(293, 623));

        panelUsuario.setBackground(new java.awt.Color(0, 153, 255));

        labelNombreUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelNombreUser.setText("nombreUsuario");
        labelNombreUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        iconSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/cerrar-sesion.png"))); // NOI18N
        iconSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombreUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(iconSalir)
                .addContainerGap())
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconSalir)
                    .addComponent(labelNombreUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOtrasVentanas.setBackground(new java.awt.Color(0, 153, 255));

        panelMenuInicio.setBackground(new java.awt.Color(0, 153, 255));
        panelMenuInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelMenuInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenuInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMenuInicioMouseExited(evt);
            }
        });

        labelMenuInicio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelMenuInicio.setText("Inicio");

        imagenMenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/boton_menu/boton_menu1.png"))); // NOI18N
        imagenMenuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenMenuInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imagenMenuInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imagenMenuInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMenuInicioLayout = new javax.swing.GroupLayout(panelMenuInicio);
        panelMenuInicio.setLayout(panelMenuInicioLayout);
        panelMenuInicioLayout.setHorizontalGroup(
            panelMenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenuInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
            .addGroup(panelMenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenMenuInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuInicioLayout.setVerticalGroup(
            panelMenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(panelMenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenMenuInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenuCardiaco.setBackground(new java.awt.Color(0, 153, 255));
        panelMenuCardiaco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelMenuCardiaco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenuCardiaco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuCardiacoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenuCardiacoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMenuCardiacoMouseExited(evt);
            }
        });

        labelMenuCardiaco.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelMenuCardiaco.setText("Sensor de ritmo cardiaco");

        imagenMenuCardiaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/boton_menu/boton_menu1.png"))); // NOI18N

        javax.swing.GroupLayout panelMenuCardiacoLayout = new javax.swing.GroupLayout(panelMenuCardiaco);
        panelMenuCardiaco.setLayout(panelMenuCardiacoLayout);
        panelMenuCardiacoLayout.setHorizontalGroup(
            panelMenuCardiacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuCardiacoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenuCardiaco, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelMenuCardiacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenMenuCardiaco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuCardiacoLayout.setVerticalGroup(
            panelMenuCardiacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuCardiacoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenuCardiaco)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(panelMenuCardiacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenMenuCardiaco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenuPresencia.setBackground(new java.awt.Color(0, 153, 255));
        panelMenuPresencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelMenuPresencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenuPresencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuPresenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenuPresenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMenuPresenciaMouseExited(evt);
            }
        });

        labelMenuPresencia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelMenuPresencia.setText("Sensor de presencia");

        imagenMenuPresencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/boton_menu/boton_menu1.png"))); // NOI18N

        javax.swing.GroupLayout panelMenuPresenciaLayout = new javax.swing.GroupLayout(panelMenuPresencia);
        panelMenuPresencia.setLayout(panelMenuPresenciaLayout);
        panelMenuPresenciaLayout.setHorizontalGroup(
            panelMenuPresenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPresenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenuPresencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
            .addGroup(panelMenuPresenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenMenuPresencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuPresenciaLayout.setVerticalGroup(
            panelMenuPresenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPresenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenuPresencia)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(panelMenuPresenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenMenuPresencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenuDetectorPuerta.setBackground(new java.awt.Color(0, 153, 255));
        panelMenuDetectorPuerta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelMenuDetectorPuerta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenuDetectorPuerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuDetectorPuertaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenuDetectorPuertaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMenuDetectorPuertaMouseExited(evt);
            }
        });

        labelMenuDetectorPuerta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelMenuDetectorPuerta.setText("Detector de puerta");

        imagenMenuPuerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/boton_menu/boton_menu1.png"))); // NOI18N

        javax.swing.GroupLayout panelMenuDetectorPuertaLayout = new javax.swing.GroupLayout(panelMenuDetectorPuerta);
        panelMenuDetectorPuerta.setLayout(panelMenuDetectorPuertaLayout);
        panelMenuDetectorPuertaLayout.setHorizontalGroup(
            panelMenuDetectorPuertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuDetectorPuertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenuDetectorPuerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
            .addGroup(panelMenuDetectorPuertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenMenuPuerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuDetectorPuertaLayout.setVerticalGroup(
            panelMenuDetectorPuertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuDetectorPuertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenuDetectorPuerta)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(panelMenuDetectorPuertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenMenuPuerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenuMensajeria.setBackground(new java.awt.Color(0, 153, 255));
        panelMenuMensajeria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelMenuMensajeria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenuMensajeria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuMensajeriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenuMensajeriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMenuMensajeriaMouseExited(evt);
            }
        });

        imagenMenuMensajeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/boton_menu/boton_menu1.png"))); // NOI18N

        labelMenuMensajeria.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelMenuMensajeria.setText("Mensajería");

        iconCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/correo.png"))); // NOI18N
        iconCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelMenuMensajeriaLayout = new javax.swing.GroupLayout(panelMenuMensajeria);
        panelMenuMensajeria.setLayout(panelMenuMensajeriaLayout);
        panelMenuMensajeriaLayout.setHorizontalGroup(
            panelMenuMensajeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuMensajeriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenuMensajeria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconCorreo)
                .addContainerGap())
            .addGroup(panelMenuMensajeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenMenuMensajeria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuMensajeriaLayout.setVerticalGroup(
            panelMenuMensajeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuMensajeriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuMensajeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconCorreo)
                    .addComponent(labelMenuMensajeria))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(panelMenuMensajeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenMenuMensajeria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout panelOtrasVentanasLayout = new javax.swing.GroupLayout(panelOtrasVentanas);
        panelOtrasVentanas.setLayout(panelOtrasVentanasLayout);
        panelOtrasVentanasLayout.setHorizontalGroup(
            panelOtrasVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
            .addComponent(panelMenuCardiaco, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
            .addComponent(panelMenuPresencia, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
            .addComponent(panelMenuDetectorPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
            .addComponent(panelMenuMensajeria, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelOtrasVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
        );
        panelOtrasVentanasLayout.setVerticalGroup(
            panelOtrasVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtrasVentanasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenuCardiaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenuPresencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenuDetectorPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelMenuMensajeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelOtrasVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelOtrasVentanasLayout.createSequentialGroup()
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 342, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelBarraIzquierdaLayout = new javax.swing.GroupLayout(panelBarraIzquierda);
        panelBarraIzquierda.setLayout(panelBarraIzquierdaLayout);
        panelBarraIzquierdaLayout.setHorizontalGroup(
            panelBarraIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzquierdaLayout.createSequentialGroup()
                .addGroup(panelBarraIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOtrasVentanas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBarraIzquierdaLayout.setVerticalGroup(
            panelBarraIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzquierdaLayout.createSequentialGroup()
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOtrasVentanas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatosVentana.setBackground(new java.awt.Color(255, 255, 255));

        panelVentanaMensajeria.setBackground(new java.awt.Color(255, 255, 255));
        panelVentanaMensajeria.setOpaque(false);

        javax.swing.GroupLayout panelVentanaMensajeriaLayout = new javax.swing.GroupLayout(panelVentanaMensajeria);
        panelVentanaMensajeria.setLayout(panelVentanaMensajeriaLayout);
        panelVentanaMensajeriaLayout.setHorizontalGroup(
            panelVentanaMensajeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1335, Short.MAX_VALUE)
        );
        panelVentanaMensajeriaLayout.setVerticalGroup(
            panelVentanaMensajeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));

        labelTituloVentana.setBackground(new java.awt.Color(255, 255, 255));
        labelTituloVentana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTituloVentana.setForeground(new java.awt.Color(0, 153, 255));
        labelTituloVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/bienvenido.png"))); // NOI18N

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1335, Short.MAX_VALUE)
            .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelTituloVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
            .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelTituloVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
        );

        panelSensores.setBackground(new java.awt.Color(255, 255, 255));

        panelPacientes.setBackground(new java.awt.Color(255, 255, 255));
        panelPacientes.setLayout(new java.awt.GridLayout(1, 0));

        panelFrameSensor.setBackground(new java.awt.Color(255, 255, 255));
        panelFrameSensor.setLayout(new java.awt.GridLayout(1, 0));

        labelTituloSensores.setBackground(new java.awt.Color(255, 255, 255));
        labelTituloSensores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTituloSensores.setForeground(new java.awt.Color(0, 153, 255));
        labelTituloSensores.setText("Título de la ventana");

        javax.swing.GroupLayout panelSensoresLayout = new javax.swing.GroupLayout(panelSensores);
        panelSensores.setLayout(panelSensoresLayout);
        panelSensoresLayout.setHorizontalGroup(
            panelSensoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFrameSensor, javax.swing.GroupLayout.DEFAULT_SIZE, 1347, Short.MAX_VALUE)
            .addGroup(panelSensoresLayout.createSequentialGroup()
                .addComponent(panelPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 1335, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelSensoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelTituloSensores, javax.swing.GroupLayout.DEFAULT_SIZE, 1347, Short.MAX_VALUE))
        );
        panelSensoresLayout.setVerticalGroup(
            panelSensoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSensoresLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(panelPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFrameSensor, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
            .addGroup(panelSensoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSensoresLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(labelTituloSensores, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(472, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelDatosVentanaLayout = new javax.swing.GroupLayout(panelDatosVentana);
        panelDatosVentana.setLayout(panelDatosVentanaLayout);
        panelDatosVentanaLayout.setHorizontalGroup(
            panelDatosVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVentanaLayout.createSequentialGroup()
                .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelDatosVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelSensores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDatosVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosVentanaLayout.createSequentialGroup()
                    .addComponent(panelVentanaMensajeria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelDatosVentanaLayout.setVerticalGroup(
            panelDatosVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDatosVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelSensores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDatosVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelVentanaMensajeria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelVentanaLayout = new javax.swing.GroupLayout(panelVentana);
        panelVentana.setLayout(panelVentanaLayout);
        panelVentanaLayout.setHorizontalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLayout.createSequentialGroup()
                .addComponent(panelBarraIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatosVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVentanaLayout.setVerticalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDatosVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconSalirMouseClicked
        PInfUI.abrirVentana(null, this, TipoVentana.LOGIN);
    }//GEN-LAST:event_iconSalirMouseClicked

    private void panelMenuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuInicioMouseClicked
        System.out.println("pinfui.interfaz.PantallaFamiliar.panelMenuInicioMouseClicked()");
        
        panelInicio.setVisible(true);
        panelFrameSensor.setVisible(false);
        panelVentanaMensajeria.setVisible(false);
        panelSensores.setVisible(false);
        
        panelInicio.setLayout(new java.awt.BorderLayout());
        panelInicio.removeAll();
        panelInicio.add(new JPanelInicio(this.usuario));
        panelInicio.revalidate();
        panelInicio.repaint();
    }//GEN-LAST:event_panelMenuInicioMouseClicked

    private void panelMenuInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuInicioMouseEntered
//        panelMenuInicio.setBackground(new java.awt.Color(0, 102, 204));
//        panelMenuInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        
        terminarHiloButton = false;
        imagenMenuInicio.setVisible(true);
        crearHiloCambioIconButton(imagenMenuInicio);
    }//GEN-LAST:event_panelMenuInicioMouseEntered

    private void panelMenuInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuInicioMouseExited
//        panelMenuInicio.setBackground(new java.awt.Color(0, 153, 255));
//        panelMenuInicio.setBorder(null);

        terminarHiloButton = true;
        imagenMenuInicio.setVisible(false);
        imagenMenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/boton_menu/boton_menu1.png")));
    }//GEN-LAST:event_panelMenuInicioMouseExited

    private void panelMenuCardiacoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuCardiacoMouseClicked
        panelInicio.setVisible(false);
        panelFrameSensor.setVisible(true);
        panelVentanaMensajeria.setVisible(false);
        panelSensores.setVisible(true);
        panelPacientes.setVisible(true);
        
        tipoSensor = TipoSensor.RITMOCARDIACO;

        labelTituloSensores.setText(PInfUI.getBundle().getString("menuRitmoCardiaco"));
        pintarGrafica();
    }//GEN-LAST:event_panelMenuCardiacoMouseClicked

    private void panelMenuCardiacoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuCardiacoMouseEntered
//        panelMenuCardiaco.setBackground(new java.awt.Color(0, 102, 204));
//        panelMenuCardiaco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        
        terminarHiloButton = false;
        imagenMenuCardiaco.setVisible(true);
        crearHiloCambioIconButton(imagenMenuCardiaco);
    }//GEN-LAST:event_panelMenuCardiacoMouseEntered

    private void panelMenuCardiacoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuCardiacoMouseExited
//        panelMenuCardiaco.setBackground(new java.awt.Color(0, 153, 255));
//        panelMenuCardiaco.setBorder(null);
        
        terminarHiloButton = true;
        imagenMenuCardiaco.setVisible(false);
        imagenMenuCardiaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/boton_menu/boton_menu1.png")));
    }//GEN-LAST:event_panelMenuCardiacoMouseExited

    private void panelMenuPresenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuPresenciaMouseClicked
        panelInicio.setVisible(false);
        panelFrameSensor.setVisible(true);
        panelVentanaMensajeria.setVisible(false);
        panelSensores.setVisible(true);
        panelPacientes.setVisible(true);
        
        tipoSensor = TipoSensor.PRESENCIA;

        labelTituloSensores.setText(PInfUI.getBundle().getString("menuPresencia"));
        recuperarPresencia();
    }//GEN-LAST:event_panelMenuPresenciaMouseClicked

    private void panelMenuPresenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuPresenciaMouseEntered
//        panelMenuPresencia.setBackground(new java.awt.Color(0, 102, 204));
//        panelMenuPresencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        terminarHiloButton = false;
        imagenMenuPresencia.setVisible(true);
        crearHiloCambioIconButton(imagenMenuPresencia);
    }//GEN-LAST:event_panelMenuPresenciaMouseEntered

    private void panelMenuPresenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuPresenciaMouseExited
//        panelMenuPresencia.setBackground(new java.awt.Color(0, 153, 255));
//        panelMenuPresencia.setBorder(null);
        
        terminarHiloButton = true;
        imagenMenuPresencia.setVisible(false);
        imagenMenuPresencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/boton_menu/boton_menu1.png")));
    }//GEN-LAST:event_panelMenuPresenciaMouseExited

    private void panelMenuDetectorPuertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuDetectorPuertaMouseClicked
        panelInicio.setVisible(false);
        panelFrameSensor.setVisible(true);
        panelVentanaMensajeria.setVisible(false);
        panelSensores.setVisible(true);
        panelPacientes.setVisible(true);
        
        tipoSensor = TipoSensor.PUERTACALLE;
        
        labelTituloSensores.setText(PInfUI.getBundle().getString("menuDetectorPuerta"));
        recuperarPuertaCalle();
    }//GEN-LAST:event_panelMenuDetectorPuertaMouseClicked

    private void panelMenuDetectorPuertaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuDetectorPuertaMouseEntered
//        panelMenuDetectorPuerta.setBackground(new java.awt.Color(0, 102, 204));
//        panelMenuDetectorPuerta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        
        terminarHiloButton = false;
        imagenMenuPuerta.setVisible(true);
        crearHiloCambioIconButton(imagenMenuPuerta);
    }//GEN-LAST:event_panelMenuDetectorPuertaMouseEntered

    private void panelMenuDetectorPuertaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuDetectorPuertaMouseExited
//        panelMenuDetectorPuerta.setBackground(new java.awt.Color(0, 153, 255));
//        panelMenuDetectorPuerta.setBorder(null);
        
        terminarHiloButton = true;
        imagenMenuPuerta.setVisible(false);
        imagenMenuPuerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/boton_menu/boton_menu1.png")));
    }//GEN-LAST:event_panelMenuDetectorPuertaMouseExited

    private void panelMenuMensajeriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMensajeriaMouseClicked
        panelInicio.setVisible(false);
        panelFrameSensor.setVisible(false);
        panelVentanaMensajeria.setVisible(true);
        panelSensores.setVisible(false);
        
        panelVentanaMensajeria.setLayout(new java.awt.BorderLayout());
        panelVentanaMensajeria.removeAll();
        panelVentanaMensajeria.add(new JPanelMensajeria(this.usuario));
        panelVentanaMensajeria.revalidate();
        panelVentanaMensajeria.repaint();
    }//GEN-LAST:event_panelMenuMensajeriaMouseClicked

    private void panelMenuMensajeriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMensajeriaMouseEntered
//        panelMenuMensajeria.setBackground(new java.awt.Color(0, 102, 204));
//        panelMenuMensajeria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        
        terminarHiloButton = false;
        imagenMenuMensajeria.setVisible(true);
        crearHiloCambioIconButton(imagenMenuMensajeria);
    }//GEN-LAST:event_panelMenuMensajeriaMouseEntered

    private void panelMenuMensajeriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMensajeriaMouseExited
//        panelMenuMensajeria.setBackground(new java.awt.Color(0, 153, 255));
//        panelMenuMensajeria.setBorder(null);
        
        terminarHiloButton = true;
        imagenMenuMensajeria.setVisible(false);
        imagenMenuMensajeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/boton_menu/boton_menu1.png")));
    }//GEN-LAST:event_panelMenuMensajeriaMouseExited

    private void imagenMenuInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenMenuInicioMouseEntered
        terminarHiloButton = false;
        imagenMenuInicio.setVisible(true);
        crearHiloCambioIconButton(imagenMenuInicio);
    }//GEN-LAST:event_imagenMenuInicioMouseEntered

    private void imagenMenuInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenMenuInicioMouseExited
        terminarHiloButton = false;
        imagenMenuInicio.setVisible(false);
    }//GEN-LAST:event_imagenMenuInicioMouseExited

    private void imagenMenuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenMenuInicioMouseClicked
        panelMenuInicioMouseClicked(evt);
    }//GEN-LAST:event_imagenMenuInicioMouseClicked

    //metodo para añadir los cambios que queramos nosotros por codigo
    private void myInitComponents(){
        panelMenuInicio.setBorder(null);
        panelMenuCardiaco.setBorder(null);
        panelMenuPresencia.setBorder(null);
        panelMenuDetectorPuerta.setBorder(null);
        panelMenuMensajeria.setBorder(null);
        terminarHiloCorreo = false;
        
        //cambiar size de las letras 
        
        labelNombreUser.setText(usuario.getNombre());
        listaLabels.add(new LabelDTO(labelNombreUser,null, labelNombreUser.getFont().getSize()));
        listaLabels.add(new LabelDTO(labelMenuMensajeria, "menuMensajeria", labelMenuMensajeria.getFont().getSize()));
        listaLabels.add(new LabelDTO(labelMenuInicio, "tituloInicio", labelMenuInicio.getFont().getSize()));
        listaLabels.add(new LabelDTO(labelMenuCardiaco, "menuRitmoCardiaco", labelMenuCardiaco.getFont().getSize()));
        listaLabels.add(new LabelDTO(labelMenuDetectorPuerta, "menuDetectorPuerta", labelMenuDetectorPuerta.getFont().getSize()));
        listaLabels.add(new LabelDTO(labelMenuPresencia, "menuPresencia", labelMenuPresencia.getFont().getSize()));
        
        dniPaciente = "";
        nombrePaciente = "";
        if(usuario != null) {
        	if(usuario.getListaAsignacion().size() > 1) {
		        for(Asignacion asignacion : usuario.getListaAsignacion()) {
		        	JButton boton = new JButton(asignacion.getUsuarioAsociado().getNombre() + " " + asignacion.getUsuarioAsociado().getApellidos());
		        	boton.setToolTipText(asignacion.getUsuarioAsociado().getDni());
		        	
		        	boton.addActionListener(new java.awt.event.ActionListener() {
		                public void actionPerformed(java.awt.event.ActionEvent evt) {
		                    jButtonActionPerformed(evt);
		                }
		            });
		        	
		        	panelPacientes.add(boton);
		        	
		        	if(dniPaciente.isEmpty()) {
		        		dniPaciente = asignacion.getUsuarioAsociado().getDni();
		        		nombrePaciente = asignacion.getUsuarioAsociado().getNombre() + " " + asignacion.getUsuarioAsociado().getApellidos();
		        	}
		        }
        	} else {
        		dniPaciente = usuario.getListaAsignacion().get(0).getUsuarioAsociado().getDni();
        		nombrePaciente = usuario.getListaAsignacion().get(0).getUsuarioAsociado().getNombre() + " " + usuario.getListaAsignacion().get(0).getUsuarioAsociado().getApellidos();
        	}
        }
        
        panelPacientes.revalidate();
        panelPacientes.repaint();
        
        panelPacientes.setVisible(false);
        
        crearHiloCambioIconCorreo(iconCorreo);

        cambiarFuentes();
        
        imagenMenuInicio.setVisible(false);
        imagenMenuCardiaco.setVisible(false);
        imagenMenuPresencia.setVisible(false);
        imagenMenuPuerta.setVisible(false);
        imagenMenuMensajeria.setVisible(false);
    }
    
    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {                                        
        System.out.println("Cargar datos de " + ((JButton) evt.getSource()).getToolTipText());
        dniPaciente = ((JButton) evt.getSource()).getToolTipText();
        nombrePaciente = ((JButton) evt.getSource()).getText();

        if(tipoSensor.equals(TipoSensor.RITMOCARDIACO)) {
            pintarGrafica();
        } else if(tipoSensor.equals(TipoSensor.PUERTACALLE)) {
            recuperarPuertaCalle();
        } else if(tipoSensor.equals(TipoSensor.PRESENCIA)) {
            recuperarPresencia();
        }

    }
    
    /**
     * Metodo encargado de pintar la grafica
     */
    private void pintarGrafica() {
    	panelFrameSensor.removeAll();
        
//        nombrePaciente = "";
//        for(Asignacion asignacion : usuario.getListaAsignacion()) {
//            if(asignacion.getUsuarioAsociado().getDni().equalsIgnoreCase(dniPaciente)){
//                nombrePaciente = asignacion.getUsuarioAsociado().getNombre();
//            }
//        }
    	panelFrameSensor.add(new JPanelRitmoCardiaco(dniPaciente, nombrePaciente));
        panelFrameSensor.revalidate();
        panelFrameSensor.repaint();
    }
    
    /**
     * Metodo encargado de recuperar todos los datos del presencia
     */
    private void recuperarPresencia() {
//    	panelVentanaPresencia.removeAll();
//    	
//    	panelVentanaPresencia.add(new JPanelPresencia(dniPaciente, nombrePaciente));
//    	panelVentanaPresencia.revalidate();
//    	panelVentanaPresencia.repaint();
    	
    	panelFrameSensor.removeAll();
    	
        
//        picker.setTextEditable(true);
//        picker.setShowYearButtons(true);
//        panelVentanaCardiaco.add((JComponent) picker);
//        
//        System.out.println(picker.getModel().getDay());
    	
    	panelFrameSensor.add(new JPanelPresencia(dniPaciente, nombrePaciente));
    	panelFrameSensor.revalidate();
    	panelFrameSensor.repaint();
    }
    
    /**
     * Metodo encargado de recuperar todos los datos de la puerta calle
     */
    private void recuperarPuertaCalle() {
    	panelFrameSensor.removeAll();
    	
    	panelFrameSensor.add(new JPanelRegistroPuerta(dniPaciente, nombrePaciente));
    	panelFrameSensor.revalidate();
    	panelFrameSensor.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconCorreo;
    private javax.swing.JLabel iconSalir;
    private javax.swing.JLabel imagenMenuCardiaco;
    private javax.swing.JLabel imagenMenuInicio;
    private javax.swing.JLabel imagenMenuMensajeria;
    private javax.swing.JLabel imagenMenuPresencia;
    private javax.swing.JLabel imagenMenuPuerta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelMenuCardiaco;
    private javax.swing.JLabel labelMenuDetectorPuerta;
    private javax.swing.JLabel labelMenuInicio;
    private javax.swing.JLabel labelMenuMensajeria;
    private javax.swing.JLabel labelMenuPresencia;
    private javax.swing.JLabel labelNombreUser;
    private javax.swing.JLabel labelTituloSensores;
    private javax.swing.JLabel labelTituloVentana;
    private javax.swing.JPanel panelBarraIzquierda;
    private javax.swing.JPanel panelDatosVentana;
    private javax.swing.JPanel panelFrameSensor;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelMenuCardiaco;
    private javax.swing.JPanel panelMenuDetectorPuerta;
    private javax.swing.JPanel panelMenuInicio;
    private javax.swing.JPanel panelMenuMensajeria;
    private javax.swing.JPanel panelMenuPresencia;
    private javax.swing.JPanel panelOtrasVentanas;
    private javax.swing.JPanel panelPacientes;
    private javax.swing.JPanel panelSensores;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JPanel panelVentana;
    private javax.swing.JPanel panelVentanaMensajeria;
    // End of variables declaration//GEN-END:variables
}
