/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pinfui.interfaz;

import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import pinfui.dto.TipoVentana;
import pinfui.entidades.Asignacion;
import pinfui.entidades.Municipio;
import pinfui.entidades.Provincia;
import pinfui.entidades.Rol;
import pinfui.entidades.Usuario;
/**
 *
 * @author ITCOM
 */
public class Registro extends javax.swing.JFrame {

    List<Provincia> provinciasLista;
    List<Municipio> municipiosLista;
    List<Rol> rolesLista;
    Usuario medicoAsignado = null;
    Usuario familiarAsignado = null;
    Usuario aEditar = null;
    boolean editar = false;
    boolean passCambiada = false;    
    
    /**
     * Constructor de la clase Registro
     * En caso de que se le pase un usuario (cuando se editan) el constructor rellenará los campos con el usuario introducido
     * @param user el usuario del cual se cargarán los datos
     */
    public Registro(Usuario user) {
        initComponents();
        buttonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/guardar.png")));
        
        
        if (user != null)
        {
            editar = true;
        }
        
        //EXTRACCION DE DATOS
        municipiosLista = PInfUI.gestorDatos.getMunicipios();
        provinciasLista = PInfUI.gestorDatos.getProvincias();
        rolesLista = PInfUI.gestorDatos.getRoles();
        
        
        
        //RELLENAR ROLES
        rolesLista.forEach((rol) -> {
            jCBRol.addItem(rol);
        });
        
        //SETEAR RENDERER DE ROLES
        jCBRol.setRenderer(new RenderComboBox());
        
        //RELLENAR PROVINCIA (los municipios se rellenan en base a la provincia escogida)
        provinciasLista.forEach((provincia) -> {
            jCBProvincia.addItem(provincia);
        });
        
        //SETEAR RENDERERES
        jCBProvincia.setRenderer(new RenderComboBox());
        jCBMunicipio.setRenderer(new RenderComboBox());

        
        //Handler de salida de la ventana
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);        
        this.addWindowListener(new WindowAdapter() {
            
            @Override
            public void windowClosing(WindowEvent e) {
                int choose = JOptionPane.showConfirmDialog(null,
                        "Seguro que quiere cancelar el formulario ?",
                        "Cancelar formulario", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (choose == JOptionPane.YES_OPTION) {
                    e.getWindow().dispose();
                    //PInfUI.abrirVentana(null, null, TipoVentana.LOGIN);
                    System.out.println("close");
                  
                } else {
                    System.out.println("do nothing");
                }
            }
        });
        jPanelSeleccionAsignacion.setVisible(false);
        
        
        
        //SI ESTA EN MODO EDITAR
        //RELLENAR CON LOS DATOS
        if (editar)        
        {
            aEditar = user;
            cargarDatosUsuario(user);
        }
            
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelHeaderWarning = new javax.swing.JLabel();
        jLabelHeader1 = new javax.swing.JLabel();
        jLabelHeader2 = new javax.swing.JLabel();
        jLabelHeader3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTFApellidos = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jLabelProvincia = new javax.swing.JLabel();
        jCBProvincia = new javax.swing.JComboBox<>();
        jLabelMunicipio = new javax.swing.JLabel();
        jCBMunicipio = new javax.swing.JComboBox<>();
        jLabelDireccion = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jLabelMovil = new javax.swing.JLabel();
        jTFMovil = new javax.swing.JTextField();
        jLabelFijo = new javax.swing.JLabel();
        jTFFijo = new javax.swing.JTextField();
        jLabelDni = new javax.swing.JLabel();
        jTFDNI = new javax.swing.JTextField();
        jLabelPass1 = new javax.swing.JLabel();
        jPFContrasena = new javax.swing.JPasswordField();
        jLabelPass2 = new javax.swing.JLabel();
        jPFRepiteContrasena = new javax.swing.JPasswordField();
        jLabelRol = new javax.swing.JLabel();
        jCBRol = new javax.swing.JComboBox<>();
        jPanelSeleccionAsignacion = new javax.swing.JPanel();
        jLabelFamiliar = new javax.swing.JLabel();
        jTFFamiliarAsignado = new javax.swing.JTextField();
        jLabelMedico = new javax.swing.JLabel();
        jTFMedicoAsignado = new javax.swing.JTextField();
        bottonSeleccionarMedico = new javax.swing.JLabel();
        bottonSeleccionarFamiliar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonGuardar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelHeaderWarning.setText("Las casillas marcadas con (*) son imprescindibles para el registro");

        jLabelHeader1.setText("Datos de usuario");

        jLabelHeader2.setText("Datos de contacto");

        jLabelHeader3.setText("Información de la cuenta");

        jLabelNombre.setText("Nombre: *");

        jTFNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(173, 173, 255), null));
        jTFNombre.setNextFocusableComponent(jTFApellidos);

        //Handler enter = guardar
        jTFNombre.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jLabelApellidos.setText("Apellidos: *");

        jTFApellidos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(173, 173, 255), null));
        jTFApellidos.setNextFocusableComponent(buttonGuardar);

        //Handler enter = guardar
        jTFApellidos.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jLabelEmail.setText("Email:");

        jTFEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(173, 173, 255), null));
        jTFEmail.setNextFocusableComponent(jTFDNI);
        //Handler enter = guardar
        jTFEmail.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jLabelProvincia.setText("Provincia: *");

        jCBProvincia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCBProvincia.setNextFocusableComponent(jCBMunicipio);
        jCBProvincia.setMaximumSize(new java.awt.Dimension(112, 112));
        jCBProvincia.setPreferredSize(new java.awt.Dimension(112, 22));
        jCBProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProvinciaActionPerformed(evt);
            }
        });
        //Handler enter = guardar
        jCBProvincia.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jLabelMunicipio.setText("Municipio *");

        jCBMunicipio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCBMunicipio.setNextFocusableComponent(jTFMovil);
        jCBMunicipio.setMaximumSize(new java.awt.Dimension(112, 112));
        jCBMunicipio.setPreferredSize(new java.awt.Dimension(112, 22));
        //Handler enter = guardar
        jCBMunicipio.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jLabelDireccion.setText("Dirección: *");

        jTFDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(173, 173, 255), null));
        jTFDireccion.setNextFocusableComponent(jTFNombre);

        //Handler enter = guardar
        jTFDireccion.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jLabelMovil.setText("Telefono Movil: *");

        jTFMovil.setNextFocusableComponent(jTFFijo);
        jTFMovil.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(173, 173, 255), null));
        //Handler enter = guardar
        jTFMovil.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jLabelFijo.setText("Telefono Fijo:");

        jTFFijo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(173, 173, 255), null));
        jTFFijo.setNextFocusableComponent(jTFDireccion);

        //Handler enter = guardar
        jTFFijo.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jLabelDni.setText("DNI: *");

        jTFDNI.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(173, 173, 255), null));
        jTFDNI.setNextFocusableComponent(jPFContrasena);
        //Handler enter = guardar
        jTFDNI.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jLabelPass1.setText("Contraseña: *");

        jPFContrasena.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(173, 173, 255), null));
        jPFContrasena.setNextFocusableComponent(jPFRepiteContrasena);
        jPFContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPFContrasenaFocusGained(evt);
            }
        });
        //Handler enter = guardar
        jPFContrasena.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jLabelPass2.setText("Repita Contraseña: *");

        jPFRepiteContrasena.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(173, 173, 255), null));
        jPFRepiteContrasena.setNextFocusableComponent(jCBRol);
        jPFRepiteContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPFRepiteContrasenaFocusGained(evt);
            }
        });
        //Handler enter = guardar
        jPFRepiteContrasena.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jLabelRol.setText("Rol: *");

        jCBRol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCBRol.setNextFocusableComponent(jCBProvincia);
        jCBRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRolActionPerformed(evt);
            }
        });
        //Handler enter = guardar
        jCBRol.addKeyListener(
            new KeyAdapter()
            {
                @Override
                public void keyPressed(KeyEvent e)
                {
                    if (e.getKeyCode()==KeyEvent.VK_ENTER)
                    {
                        guardar();
                    }
                }
            }
        );

        jPanelSeleccionAsignacion.setBackground(new java.awt.Color(255, 255, 255));

        jLabelFamiliar.setText("Familiar Asignado: *");

        jTFFamiliarAsignado.setEditable(false);

        jLabelMedico.setText("Medico Asignado: *");

        jTFMedicoAsignado.setEditable(false);

        bottonSeleccionarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/es_ES/lupaBuscar.png"))); // NOI18N
        bottonSeleccionarMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bottonSeleccionarMedico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bottonSeleccionarMedicoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bottonSeleccionarMedicoFocusLost(evt);
            }
        });
        bottonSeleccionarMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottonSeleccionarMedicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bottonSeleccionarMedicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bottonSeleccionarMedicoMouseExited(evt);
            }
        });
        bottonSeleccionarMedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bottonSeleccionarMedicoKeyPressed(evt);
            }
        });
        bottonSeleccionarMedico.setNextFocusableComponent(bottonSeleccionarFamiliar);

        bottonSeleccionarFamiliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/es_ES/lupaBuscar.png"))); // NOI18N
        bottonSeleccionarFamiliar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bottonSeleccionarFamiliar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bottonSeleccionarFamiliarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bottonSeleccionarFamiliarFocusLost(evt);
            }
        });
        bottonSeleccionarFamiliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottonSeleccionarFamiliarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bottonSeleccionarFamiliarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bottonSeleccionarFamiliarMouseExited(evt);
            }
        });
        bottonSeleccionarFamiliar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bottonSeleccionarFamiliarKeyPressed(evt);
            }
        });
        bottonSeleccionarFamiliar.setNextFocusableComponent(jCBProvincia);

        javax.swing.GroupLayout jPanelSeleccionAsignacionLayout = new javax.swing.GroupLayout(jPanelSeleccionAsignacion);
        jPanelSeleccionAsignacion.setLayout(jPanelSeleccionAsignacionLayout);
        jPanelSeleccionAsignacionLayout.setHorizontalGroup(
            jPanelSeleccionAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSeleccionAsignacionLayout.createSequentialGroup()
                .addGroup(jPanelSeleccionAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFamiliar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSeleccionAsignacionLayout.createSequentialGroup()
                        .addGroup(jPanelSeleccionAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSeleccionAsignacionLayout.createSequentialGroup()
                                .addComponent(jTFMedicoAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bottonSeleccionarMedico))
                            .addGroup(jPanelSeleccionAsignacionLayout.createSequentialGroup()
                                .addComponent(jTFFamiliarAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bottonSeleccionarFamiliar)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSeleccionAsignacionLayout.setVerticalGroup(
            jPanelSeleccionAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionAsignacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMedico)
                .addGroup(jPanelSeleccionAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSeleccionAsignacionLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTFMedicoAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSeleccionAsignacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bottonSeleccionarMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addComponent(jLabelFamiliar)
                .addGroup(jPanelSeleccionAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSeleccionAsignacionLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTFFamiliarAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSeleccionAsignacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bottonSeleccionarFamiliar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buttonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/es_ES/guardar.png"))); // NOI18N
        buttonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonGuardar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buttonGuardarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                buttonGuardarFocusLost(evt);
            }
        });
        buttonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonGuardarMouseExited(evt);
            }
        });
        buttonGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonGuardarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(buttonGuardar)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(buttonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelSeleccionAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelPass2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jTFDNI, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPFRepiteContrasena, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBRol, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPass1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelRol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFijo)
                                    .addComponent(jLabelMovil)
                                    .addComponent(jLabelDireccion)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTFMovil, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFFijo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabelNombre))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCBProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelMunicipio)
                                            .addComponent(jCBMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelApellidos)
                                            .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jPFContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jSeparator1)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelHeader1)
                                    .addGap(58, 58, 58)
                                    .addComponent(jLabelHeader2)
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabelHeader3))
                                .addComponent(jLabelHeaderWarning))
                            .addGap(22, 22, 22)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProvincia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEmail)
                        .addComponent(jLabelNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDni)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMunicipio)
                        .addComponent(jLabelApellidos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPass1)
                    .addComponent(jLabelMovil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPFContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPass2)
                    .addComponent(jLabelFijo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFFijo)
                    .addComponent(jPFRepiteContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRol)
                    .addComponent(jLabelDireccion))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSeleccionAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(162, 162, 162))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelHeaderWarning)
                    .addGap(54, 54, 54)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelHeader2)
                                .addComponent(jLabelHeader3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabelHeader1))
                    .addGap(672, 672, 672)))
        );

        this.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    /**
     * Metodo para rellenar combobox municipio basandonos en provincia escogida
     * @param evt 
     */
    private void jCBProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProvinciaActionPerformed
        jCBMunicipio.removeAllItems();
        Provincia aux = (Provincia)jCBProvincia.getSelectedItem();

        for (Municipio municipio : municipiosLista) {
            if (municipio.getId_Provincia() == aux.getId_Provincia())
            {
                jCBMunicipio.addItem(municipio);
            }
        }       
    }//GEN-LAST:event_jCBProvinciaActionPerformed

    private void jCBRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRolActionPerformed
        if (((Rol)jCBRol.getSelectedItem()).getId_Rol() == 4)
        {
            jPanelSeleccionAsignacion.setVisible(true);
            jCBRol.setNextFocusableComponent(bottonSeleccionarMedico);            
        } 
        else
        {
            jCBRol.setNextFocusableComponent(jCBProvincia);
            jPanelSeleccionAsignacion.setVisible(false);
        }
    }//GEN-LAST:event_jCBRolActionPerformed

    private void buttonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGuardarMouseExited
        buttonGuardar
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/guardar.png")));
    }//GEN-LAST:event_buttonGuardarMouseExited

    private void buttonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGuardarMouseEntered
         buttonGuardar
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/guardar_hover.png")));
    }//GEN-LAST:event_buttonGuardarMouseEntered

    private void buttonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGuardarMouseClicked
        guardar();
    }//GEN-LAST:event_buttonGuardarMouseClicked

    private void jPFContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPFContrasenaFocusGained
        jPFContrasena.setText("");
        jPFRepiteContrasena.setText("");
        passCambiada = true;
//        jLabelHeader2.setText("FUNCA");
    }//GEN-LAST:event_jPFContrasenaFocusGained

    private void jPFRepiteContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPFRepiteContrasenaFocusGained
        jPFRepiteContrasena.setText("");
    }//GEN-LAST:event_jPFRepiteContrasenaFocusGained

    private void buttonGuardarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buttonGuardarFocusGained
        buttonGuardar
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/guardar_hover.png")));
    }//GEN-LAST:event_buttonGuardarFocusGained

    private void buttonGuardarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buttonGuardarFocusLost
        buttonGuardar
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/guardar.png")));
    }//GEN-LAST:event_buttonGuardarFocusLost

    private void buttonGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonGuardarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE)
            guardar();
        else if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            guardar();
    }//GEN-LAST:event_buttonGuardarKeyPressed

    private void bottonSeleccionarMedicoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bottonSeleccionarMedicoFocusGained
        bottonSeleccionarMedico
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/lupaBuscar_hover.png")));
    }//GEN-LAST:event_bottonSeleccionarMedicoFocusGained

    private void bottonSeleccionarMedicoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bottonSeleccionarMedicoFocusLost
        bottonSeleccionarMedico
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/lupaBuscar.png")));
    }//GEN-LAST:event_bottonSeleccionarMedicoFocusLost

    private void bottonSeleccionarMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonSeleccionarMedicoMouseClicked
        setMedico();
    }//GEN-LAST:event_bottonSeleccionarMedicoMouseClicked

    private void bottonSeleccionarMedicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonSeleccionarMedicoMouseEntered
        bottonSeleccionarMedico
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/lupaBuscar_hover.png")));
    }//GEN-LAST:event_bottonSeleccionarMedicoMouseEntered

    private void bottonSeleccionarMedicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonSeleccionarMedicoMouseExited
        bottonSeleccionarMedico
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/lupaBuscar.png")));
    }//GEN-LAST:event_bottonSeleccionarMedicoMouseExited

    private void bottonSeleccionarMedicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bottonSeleccionarMedicoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE)
            setMedico();
        else if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            guardar();
    }//GEN-LAST:event_bottonSeleccionarMedicoKeyPressed

    private void bottonSeleccionarFamiliarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bottonSeleccionarFamiliarFocusGained
        bottonSeleccionarFamiliar
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/lupaBuscar_hover.png")));
    }//GEN-LAST:event_bottonSeleccionarFamiliarFocusGained

    private void bottonSeleccionarFamiliarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bottonSeleccionarFamiliarFocusLost
        bottonSeleccionarFamiliar
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/lupaBuscar.png")));
    }//GEN-LAST:event_bottonSeleccionarFamiliarFocusLost

    private void bottonSeleccionarFamiliarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonSeleccionarFamiliarMouseClicked
        setFamiliar();
    }//GEN-LAST:event_bottonSeleccionarFamiliarMouseClicked

    private void bottonSeleccionarFamiliarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonSeleccionarFamiliarMouseEntered
        bottonSeleccionarFamiliar
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/lupaBuscar_hover.png")));
    }//GEN-LAST:event_bottonSeleccionarFamiliarMouseEntered

    private void bottonSeleccionarFamiliarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonSeleccionarFamiliarMouseExited
        bottonSeleccionarFamiliar
        .setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/botones/" + PInfUI.bundle.getLocale() + "/lupaBuscar.png")));
    }//GEN-LAST:event_bottonSeleccionarFamiliarMouseExited

    private void bottonSeleccionarFamiliarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bottonSeleccionarFamiliarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE)
            setFamiliar();
        else if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            guardar();
    }//GEN-LAST:event_bottonSeleccionarFamiliarKeyPressed

    
    /**
     * Metodo que se encarga de extraer y establecer los valores de los campos con los valores del usuario que ha sido recibido como parametro
     * Las asignaciones se rellenan haciendo llamadas adicionales
     * @param user Usuario recibido con el cual se rellenaran los campos
     */
    private void cargarDatosUsuario(Usuario user) {
    	

        //RELLENAR TEXTFIELDS
        jTFEmail.setText(user.getEmail());
        jTFDNI.setText(user.getDni());        
        jTFNombre.setText(user.getNombre());
        jTFApellidos.setText(user.getApellidos());
        jTFMovil.setText(user.getTlf_Movil());
        jTFFijo.setText(user.getTlf_Fijo());
        jTFDireccion.setText(user.getDireccion());
        
        //Estas dos se rellenan falsamente porque no se pueden traer los datos tal cual
        //ES UNA CONTRASEÑA RARA PARA QUE EL USUARIO NO LA PONGA SIN QUERER Y NO SE LE UPDATEE LA PASS
        jPFContrasena.setText("nosepuede"); 
        jPFRepiteContrasena.setText("nosepuede");


        //RELLENAR COMBOBOXES
        jCBProvincia.getModel().setSelectedItem(user.getMunicipio().getProvincia());
        jCBMunicipio.getModel().setSelectedItem(user.getMunicipio());
        jCBRol.getModel().setSelectedItem(user.getRol());    
        


        //RELLENAR ASIGNACIONES
//            (1,'Medico - Paciente / Paciente - Medico'),
//            (2,'Familiar - Paciente / Paciente - Familiar');
        if(user.getRol().getId_Rol() == 4)
        {
            for (Asignacion asig : user.getListaAsignacion())
            {
                if (asig.getId_Tipo() == 1) 
                {
                    this.medicoAsignado = asig.getUsuarioAsignado();
                    jTFMedicoAsignado.setText
                    (
                            this.medicoAsignado.getApellidos() +
                            " " +
                            this.medicoAsignado.getNombre()
                    );
                }                    
                else if (asig.getId_Tipo() == 2)
                {
                    this.familiarAsignado = asig.getUsuarioAsignado();
                    jTFFamiliarAsignado.setText
                    (
                            this.familiarAsignado.getApellidos() +
                            " " +
                            this.familiarAsignado.getNombre()
                    );
                }                    
            }                
        }
        
        
    }

    
    /**
     * Funcion para setear medico asignado
     * Esto solo pasa si el rol escogido es el de paciente
     * Utiliza una llamada a JPanelFiltro para conseguir el usuario
     */
    private void setMedico()
    {
        JPanelFiltro jPF = new JPanelFiltro(2, null, false, false);
        this.medicoAsignado= getUser(jPF);
        //System.out.println(this.medicoAsignado.getDni());
        if (this.medicoAsignado != null) 
            jTFMedicoAsignado.setText
            (
                    this.medicoAsignado.getApellidos() +
                    " " +
                    this.medicoAsignado.getNombre()
            );
    }
    
    /**
     * Funcion para setear familiar asignado
     * Esto solo pasa si el rol escogido es el de paciente
     * Utiliza una llamada a JPanelFiltro para conseguir el usuario
     */
    private void setFamiliar()
    {
        JPanelFiltro jPF = new JPanelFiltro(3, null, false, false);
        this.familiarAsignado = getUser(jPF);
        //System.out.println(this.familiarAsociado.getDni());
        if (this.familiarAsignado != null)
            jTFFamiliarAsignado.setText
            (
                    this.familiarAsignado.getApellidos() +
                    " " +
                    this.familiarAsignado.getNombre()
            );
    }
    
    /**
     * Guncion para guardar los datos tanto si es una edición como un nuevo registro 
     */
    private void guardar()
    {
        //Comprobar que las casillas obligatorias esten rellenadas
        // LA ULTIMA PARTE DEL IF CUMPRUEBA SI EL ROL ES 4 (OSEA PACIENTE) Y SI ES 4 DEBE RELLENAR LAS CASILLAS DE ASOCIACION
        if (jTFNombre.getText().isEmpty() ||
            jTFApellidos.getText().isEmpty() ||
            jTFDireccion.getText().isEmpty() ||
            jTFMovil.getText().isEmpty() ||
            jTFDNI.getText().isEmpty() ||
            jPFContrasena.getText().isEmpty() ||
            jPFRepiteContrasena.getText().isEmpty() ||
            (
                ((Rol)jCBRol.getSelectedItem()).getId_Rol() == 4 &&
                (
                    jTFFamiliarAsignado.getText().isEmpty() ||
                    jTFMedicoAsignado.getText().isEmpty()
                )
            )
        )
        JOptionPane.showMessageDialog(null ,"Tienes que rellenar todas las casillas marcadas con (*)", "Error", ERROR_MESSAGE);

        else
        {
            //Comprobar que la contraseña sea igual en ambos campos
            if (!Arrays.equals(jPFContrasena.getPassword(), jPFRepiteContrasena.getPassword()))
            JOptionPane.showMessageDialog(null ,"Has puesto contraseñas diferentes", "Error", ERROR_MESSAGE);
            else
            {
                Usuario user = null;
                String telefonoFijo = null;
                String email = null;

                if (!jTFFijo.getText().isEmpty())
                telefonoFijo = jTFFijo.getText();
                if (!jTFEmail.getText().isEmpty())
                email = jTFEmail.getText();

                //Crear usuario y llamar al registro
                user = new Usuario
                (
                    jTFDNI.getText(),
                    jTFNombre.getText(),
                    jTFApellidos.getText(),
                    email,
                    jTFMovil.getText(),
                    (Municipio)jCBMunicipio.getSelectedItem(),
                    (Provincia)jCBProvincia.getSelectedItem(),
                    jTFDireccion.getText(),
                    (Rol)jCBRol.getSelectedItem(),
                    telefonoFijo
                );

                //Si el usuario es paciente hay que crear asignaciones
                //El paciente siempre debera asignar un familiar
                //1 = medico - paciente
                //2 = familiar - paciente
                if (((Rol)jCBRol.getSelectedItem()).getId_Rol() == 4)
                {
                    Asignacion pacienteMedico = new Asignacion(user, this.medicoAsignado, 1);
                    Asignacion pacienteFamiliar = new Asignacion(user, this.familiarAsignado, 2);
                    List<Asignacion> listaAsignacion = new ArrayList<>();
                    listaAsignacion.add(pacienteMedico);
                    listaAsignacion.add(pacienteFamiliar);
                    PInfUI.gestorDatos.registroAsignacion(editar, listaAsignacion);
                }
                //Llamar al registro pasandole el usuario y la contraseña
                if(PInfUI.gestorDatos.registroUsuario(editar, passCambiada, user, jPFContrasena.getText(), aEditar))
                {
                    JOptionPane.showMessageDialog(null, "Guardado con exito", "Information", INFORMATION_MESSAGE);
                    PantallaAdministrador.updatePanel();
                }
                else
                    JOptionPane.showMessageDialog(null, "El DNI introducido ya existe", "Error", ERROR_MESSAGE);
                

                //CERRAR VENTANA
                this.dispose();
            }
        }
    }
    
    private Usuario getUser(JPanelFiltro jPF){
        int result = JOptionPane.showConfirmDialog(null, jPF, "Busqueda de Usuario", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION)
            return jPF.getUserSelected();
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bottonSeleccionarFamiliar;
    private javax.swing.JLabel bottonSeleccionarMedico;
    private javax.swing.JLabel buttonGuardar;
    private javax.swing.JComboBox<Municipio> jCBMunicipio;
    private javax.swing.JComboBox<Provincia> jCBProvincia;
    private javax.swing.JComboBox<Rol> jCBRol;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFamiliar;
    private javax.swing.JLabel jLabelFijo;
    private javax.swing.JLabel jLabelHeader1;
    private javax.swing.JLabel jLabelHeader2;
    private javax.swing.JLabel jLabelHeader3;
    private javax.swing.JLabel jLabelHeaderWarning;
    private javax.swing.JLabel jLabelMedico;
    private javax.swing.JLabel jLabelMovil;
    private javax.swing.JLabel jLabelMunicipio;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPass1;
    private javax.swing.JLabel jLabelPass2;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JPasswordField jPFContrasena;
    private javax.swing.JPasswordField jPFRepiteContrasena;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelSeleccionAsignacion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFApellidos;
    private javax.swing.JTextField jTFDNI;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFFamiliarAsignado;
    private javax.swing.JTextField jTFFijo;
    private javax.swing.JTextField jTFMedicoAsignado;
    private javax.swing.JTextField jTFMovil;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}
