/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pinfui.interfaz;

import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author SaFteiNZz
 */
public class PantallaUsuario extends javax.swing.JFrame {

    private boolean terminarHiloCorreo = false;
    private boolean terminarHiloButton = false;
    
    /**
     * Creates new form PantallaUsuario
     */
    public PantallaUsuario() {
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelVentana = new javax.swing.JPanel();
        panelBarraIzquierda = new javax.swing.JPanel();
        panelUsuario = new javax.swing.JPanel();
        labelNombreUser = new javax.swing.JLabel();
        iconSalir = new javax.swing.JLabel();
        panelOtrasVentanas = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        panelVentanaInicio = new javax.swing.JPanel();
        labelVentanaInicio = new javax.swing.JLabel();
        panelVentanaOtra = new javax.swing.JPanel();
        labelOtraVentana = new javax.swing.JLabel();
        panelVetananaMensajeria = new javax.swing.JPanel();
        labelVentanaMensajeria = new javax.swing.JLabel();
        iconCorreo = new javax.swing.JLabel();
        panelDatosVentana = new javax.swing.JPanel();
        labelTituloVentana = new javax.swing.JLabel();
        jButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelVentana.setBackground(new java.awt.Color(255, 255, 255));

        panelBarraIzquierda.setBackground(new java.awt.Color(0, 153, 255));

        panelUsuario.setBackground(new java.awt.Color(0, 153, 255));

        labelNombreUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelNombreUser.setText("nombreUsuario");
        labelNombreUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        iconSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/cerrar-sesion.png"))); // NOI18N
        iconSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombreUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(iconSalir)
                .addContainerGap())
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconSalir)
                    .addComponent(labelNombreUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOtrasVentanas.setBackground(new java.awt.Color(0, 153, 255));

        panelVentanaInicio.setBackground(new java.awt.Color(0, 153, 255));
        panelVentanaInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelVentanaInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelVentanaInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelVentanaInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelVentanaInicioMouseExited(evt);
            }
        });

        labelVentanaInicio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelVentanaInicio.setText("Inicio");

        javax.swing.GroupLayout panelVentanaInicioLayout = new javax.swing.GroupLayout(panelVentanaInicio);
        panelVentanaInicio.setLayout(panelVentanaInicioLayout);
        panelVentanaInicioLayout.setHorizontalGroup(
            panelVentanaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVentanaInicio)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        panelVentanaInicioLayout.setVerticalGroup(
            panelVentanaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVentanaInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVentanaOtra.setBackground(new java.awt.Color(0, 153, 255));
        panelVentanaOtra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelVentanaOtra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelVentanaOtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelVentanaOtraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelVentanaOtraMouseExited(evt);
            }
        });

        labelOtraVentana.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelOtraVentana.setText("Otra ventana");

        javax.swing.GroupLayout panelVentanaOtraLayout = new javax.swing.GroupLayout(panelVentanaOtra);
        panelVentanaOtra.setLayout(panelVentanaOtraLayout);
        panelVentanaOtraLayout.setHorizontalGroup(
            panelVentanaOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaOtraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOtraVentana)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        panelVentanaOtraLayout.setVerticalGroup(
            panelVentanaOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaOtraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOtraVentana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVetananaMensajeria.setBackground(new java.awt.Color(0, 153, 255));
        panelVetananaMensajeria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelVetananaMensajeria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelVetananaMensajeria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelVetananaMensajeriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelVetananaMensajeriaMouseExited(evt);
            }
        });

        labelVentanaMensajeria.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelVentanaMensajeria.setText("Mensajería");

        iconCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/correo.png"))); // NOI18N
        iconCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelVetananaMensajeriaLayout = new javax.swing.GroupLayout(panelVetananaMensajeria);
        panelVetananaMensajeria.setLayout(panelVetananaMensajeriaLayout);
        panelVetananaMensajeriaLayout.setHorizontalGroup(
            panelVetananaMensajeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVetananaMensajeriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVentanaMensajeria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconCorreo)
                .addContainerGap())
        );
        panelVetananaMensajeriaLayout.setVerticalGroup(
            panelVetananaMensajeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVetananaMensajeriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVetananaMensajeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconCorreo)
                    .addComponent(labelVentanaMensajeria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelOtrasVentanasLayout = new javax.swing.GroupLayout(panelOtrasVentanas);
        panelOtrasVentanas.setLayout(panelOtrasVentanasLayout);
        panelOtrasVentanasLayout.setHorizontalGroup(
            panelOtrasVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentanaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelVentanaOtra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelVetananaMensajeria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelOtrasVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
        );
        panelOtrasVentanasLayout.setVerticalGroup(
            panelOtrasVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtrasVentanasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVentanaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVentanaOtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(panelVetananaMensajeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelOtrasVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelOtrasVentanasLayout.createSequentialGroup()
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 342, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelBarraIzquierdaLayout = new javax.swing.GroupLayout(panelBarraIzquierda);
        panelBarraIzquierda.setLayout(panelBarraIzquierdaLayout);
        panelBarraIzquierdaLayout.setHorizontalGroup(
            panelBarraIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelOtrasVentanas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBarraIzquierdaLayout.setVerticalGroup(
            panelBarraIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzquierdaLayout.createSequentialGroup()
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOtrasVentanas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatosVentana.setBackground(new java.awt.Color(255, 255, 255));

        labelTituloVentana.setBackground(new java.awt.Color(255, 255, 255));
        labelTituloVentana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTituloVentana.setForeground(new java.awt.Color(0, 153, 255));
        labelTituloVentana.setText("Título de la ventana");

        jButton.setBackground(new java.awt.Color(0, 153, 255));
        jButton.setText("Guardar");
        jButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton.setBorderPainted(false);
        jButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton.setFocusable(false);
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Button");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 16, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/submit.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 290, 110);

        javax.swing.GroupLayout panelDatosVentanaLayout = new javax.swing.GroupLayout(panelDatosVentana);
        panelDatosVentana.setLayout(panelDatosVentanaLayout);
        panelDatosVentanaLayout.setHorizontalGroup(
            panelDatosVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVentanaLayout.createSequentialGroup()
                .addGroup(panelDatosVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosVentanaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTituloVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE))
                    .addGroup(panelDatosVentanaLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelDatosVentanaLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosVentanaLayout.setVerticalGroup(
            panelDatosVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVentanaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloVentana)
                .addGap(74, 74, 74)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout panelVentanaLayout = new javax.swing.GroupLayout(panelVentana);
        panelVentana.setLayout(panelVentanaLayout);
        panelVentanaLayout.setHorizontalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLayout.createSequentialGroup()
                .addComponent(panelBarraIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatosVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVentanaLayout.setVerticalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDatosVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelVentanaOtraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVentanaOtraMouseEntered
        panelVentanaOtra.setBackground(new java.awt.Color(0, 102, 204));
        panelVentanaOtra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_panelVentanaOtraMouseEntered

    private void panelVentanaOtraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVentanaOtraMouseExited
        panelVentanaOtra.setBackground(new java.awt.Color(0, 153, 255));
        panelVentanaOtra.setBorder(null);
    }//GEN-LAST:event_panelVentanaOtraMouseExited

    private void panelVentanaInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVentanaInicioMouseEntered
        panelVentanaInicio.setBackground(new java.awt.Color(0, 102, 204));
        panelVentanaInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_panelVentanaInicioMouseEntered

    private void panelVentanaInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVentanaInicioMouseExited
        panelVentanaInicio.setBackground(new java.awt.Color(0, 153, 255));
        panelVentanaInicio.setBorder(null);
    }//GEN-LAST:event_panelVentanaInicioMouseExited

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActionPerformed

    private void panelVetananaMensajeriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVetananaMensajeriaMouseEntered
        panelVetananaMensajeria.setBackground(new java.awt.Color(0, 102, 204));
        panelVetananaMensajeria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_panelVetananaMensajeriaMouseEntered

    private void panelVetananaMensajeriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVetananaMensajeriaMouseExited
        panelVetananaMensajeria.setBackground(new java.awt.Color(0, 153, 255));
        panelVetananaMensajeria.setBorder(null);
    }//GEN-LAST:event_panelVetananaMensajeriaMouseExited

    private void iconSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconSalirMouseClicked
        PInfUI.ventanaUser.hide();
        PInfUI.ventanaLogIn.setVisible(true);
    }//GEN-LAST:event_iconSalirMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
         terminarHiloButton = false;
         
         crearHiloCambioIconButton();
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        terminarHiloButton = true;
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/submit.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    //metodo para añadir los cambios que queramos nosotros por codigo
    private void myInitComponents(){
        panelVentanaOtra.setBorder(null);
        panelVentanaInicio.setBorder(null);
        panelVetananaMensajeria.setBorder(null);
        terminarHiloCorreo = false;
        
        //cambiar size de las letras 
        cambiarFuentes();
        
        crearHiloCambioIconCorreo();
    }
    
    private void cambiarFuentes(){
        List<javax.swing.JLabel> listaLabels = new ArrayList<javax.swing.JLabel>();
        listaLabels.add(labelNombreUser);
        listaLabels.add(labelTituloVentana);
        listaLabels.add(labelVentanaInicio);
        listaLabels.add(labelVentanaMensajeria);
        listaLabels.add(labelOtraVentana);
        
        for(javax.swing.JLabel label : listaLabels){
            label.setFont(cambiarSize(label.getFont().getSize(), 10));
        }
        
        List<javax.swing.JButton> listaBotones = new ArrayList<javax.swing.JButton>();
        listaBotones.add(jButton);
        
        for(javax.swing.JButton boton : listaBotones){
            boton.setFont(cambiarSize(boton.getFont().getSize(), 10));
        }
    }
    
    private java.awt.Font cambiarSize(int sizeActual, int suma){
        return new java.awt.Font("Tahoma", 0, sizeActual + suma);
    }
    
    private void crearHiloCambioIconButton(){
        // Creacion de un hilo para cambiar la imagen del correo cuando tengas notificaciones nuevas - Asi llama mas la atencion
        new Thread(new Runnable() {
            public void run() {
                
                //Se controlara el tiempo para que cambie el icono cada segundo
                Calendar proximaEjecucion = Calendar.getInstance();
                proximaEjecucion.setTime(new Date());
                proximaEjecucion.add(Calendar.MILLISECOND, 20);
                
                int contador = 1;
                //Siempre que terminarHiloCorreo este a false se ejecutara el hilo
                while(!terminarHiloButton && contador <10){
                    Calendar fechaActual = Calendar.getInstance();
                    fechaActual.setTime(new Date());
                    
                    if(fechaActual.compareTo(proximaEjecucion) >= 0){
                        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/submit" + contador + ".png")));
                        contador++;
                        proximaEjecucion.setTime(new Date());
                        proximaEjecucion.add(Calendar.MILLISECOND, 20);
                    }

                    try {
                        java.lang.Thread.sleep(100);
                    }catch(Exception e) { }
                }
                
                if(contador == 10){
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/submit10.png")));
                }
            }
        }).start();
    }
    
    private void crearHiloCambioIconCorreo(){
        // Creacion de un hilo para cambiar la imagen del correo cuando tengas notificaciones nuevas - Asi llama mas la atencion
        new Thread(new Runnable() {
            public void run() {
                
                //Se controlara el tiempo para que cambie el icono cada segundo
                Calendar proximaEjecucion = Calendar.getInstance();
                proximaEjecucion.setTime(new Date());
                proximaEjecucion.add(Calendar.SECOND, 1);
                
                boolean cambioAlert = true;
                
                //Siempre que terminarHiloCorreo este a false se ejecutara el hilo
                while(!terminarHiloCorreo){
                    Calendar fechaActual = Calendar.getInstance();
                    fechaActual.setTime(new Date());
                    
                    if(fechaActual.compareTo(proximaEjecucion) >= 0){
                        if(cambioAlert){
                            
                            //Esta parte es la que se encarga de ejecutarse como un hilo
                            SwingUtilities.invokeLater(new Runnable() {

                                public void run() {
                                    iconCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/correo-alert.png")));
                                }
                            });
                            cambioAlert = false;
                        } else {
                            SwingUtilities.invokeLater(new Runnable() {

                                public void run() {
                                    iconCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/correo.png")));
                                }
                            });
                            cambioAlert = true;
                        }
                        
                        proximaEjecucion.setTime(new Date());
                        proximaEjecucion.add(Calendar.SECOND, 2);
                    }

                    try {
                        java.lang.Thread.sleep(100);
                    }catch(Exception e) { }
                }
            }
        }).start();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconCorreo;
    private javax.swing.JLabel iconSalir;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelNombreUser;
    private javax.swing.JLabel labelOtraVentana;
    private javax.swing.JLabel labelTituloVentana;
    private javax.swing.JLabel labelVentanaInicio;
    private javax.swing.JLabel labelVentanaMensajeria;
    private javax.swing.JPanel panelBarraIzquierda;
    private javax.swing.JPanel panelDatosVentana;
    private javax.swing.JPanel panelOtrasVentanas;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JPanel panelVentana;
    private javax.swing.JPanel panelVentanaInicio;
    private javax.swing.JPanel panelVentanaOtra;
    private javax.swing.JPanel panelVetananaMensajeria;
    // End of variables declaration//GEN-END:variables
}
